fontra/fontra

- src/fontra/views/editor/edit-behavior.js
> Round coordinates and component origin when dragging

- src/fontra/backends/designspace.py
- src/fontra/backends/truetype.py
- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/scene-model.js
- test-py/test_font.py
> Expose and use units per em

- README.md
- src/fontra/__main__.py
- src/fontra/core/server.py
> Auto launch browser with --launch option

- src/fontra/views/editor/edit-behavior.js
> If there's no interesection, return the next reasonable thing

- src/fontra/__main__.py
> Avoid adding the same sub-parser multiple times

- src/fontra/backends/designspace.py
> Fix one `Component` attribute access

- pyproject.toml
- setup.py
In an attempt to resolve #141 I played with using hatch instead of setuptools. We should probably move into that direction anyway.
@madig, do I remember correctly that you have some experience with hatch? If so, could you have a look if I didn't mess up anything obvious? Or less obvious.
It should probably have an sdist section.
> Use hatch instead of setuptools

- src/fontra/client/core/utils.js
- src/fontra/client/core/vector.js
- src/fontra/views/editor/edit-tools-pen.js
- src/fontra/views/editor/edit-tools-pointer.js
> Toggle smooth flag when double-clicking points

- src/fontra/client/core/context-menu.js
- src/fontra/client/css/context-menu.css
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
> Add context menu

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
> Implement reverse contour direction

- src/fontra/client/core/changes.js
- src/fontra/client/core/font-controller.js
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/var-path.js
- src/fontra/core/changes.py
- src/fontra/views/editor/scene-controller.js
Implement a (shallow) decompose components, hook up to contextual menu.
This implements the shallow part of #161.
> Decompose components

- src/fontra/client/core/mouse-tracker.js
- src/fontra/client/core/queue-iterator.js
- src/fontra/client/core/ui-form.js
- src/fontra/views/editor/edit-tools-pointer.js
- test-js/test-queue-iterator.js
Add QueueIterator class, and use it to replace two specialized async queues.
> Add generic async queue iterator class

- requirements.txt
- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/core/glyphnames.py
- src/fontra/views/editor/editor.js
- test-py/test_glyphnames.py
- add server API for getting a glyph name for a code point
- on the server side, for now use the Glyphs.app glyph naming scheme
> Ask server for suggested glyph name for undefined chars

- src/fontra/client/core/value-controller.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-model.js
- test-js/test-value-controller.js
The ValueController object is an attempt at abstraction between UI and value. Setting the value goes via a `controller.set()` method on the value controller, observing changes goes via callbacks set with `controller.addObserver()`.
> Add ValueController class

- src/fontra/backends/designspace.py
- src/fontra/backends/opentype.py
- src/fontra/core/classes.py
- src/fontra/views/editor/editor.js
- test-py/test_font.py
The (reverse) cmap is/will be managed separately.
> Remove glyph.unicodes

- README.md
Start writing a roadmap. Will edit more before merging.
> Start writing a public roadmap [wip]

- src/fontra/backends/designspace.py
> Don't add a source to the local designspace if it is in fact a global

- src/fontra/client/core/cmap.js
- src/fontra/client/core/font-controller.js
- test-js/test-cmap.js
- Add a cmap wrapper that can keep a matching reverse cmap up-to-date
- Add `makeReverseMapping(cmap)` helper function
- Add `makeMappingFromReverseMapping(cmap)` helper function
> Cmap wrapper

- src/fontra/core/changes.py
- test-py/test_changes.py
- Unify addPathToPattern and addPatternToPattern
- Unify removePathFromPattern and removePatternFromPattern
- Add pathToPattern helper func
> Pattern add unify

- src/fontra/core/changes.py
- src/fontra/core/fonthandler.py
- test-py/test_changes.py
- Instead, return fresh objects
- Also: rename `removeFromPattern` to subtractFromPattern`
- Make some functions private that should have been private all along
> Don't modify patterns in-place

- src/fontra/core/fonthandler.py
- Refactor and rename updateLocalData to updateLocalDataAndWriteToBackend
- Implement not-yet-tested handling of changes yield by watchExternalChanges
> Refactor and rename updateLocalData

- src/fontra/backends/designspace.py
- src/fontra/client/core/font-controller.js
- src/fontra/client/core/remote.js
- src/fontra/client/core/utils.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/editor.js
> “Create new glyph” implementation

- README.md
Add additional setup instructions in order to run `pytest` and `npm test`
> Update setup instructions in the Readme

- src/fontra/core/fonthandler.py
Work around https://github.com/samuelcolvin/watchfiles/issues/200
> On exit, suppress a buggy exception from watchfiles

- src/fontra/views/editor/editor.js
> Use querySelectorAll in some places

- src/fontra/views/editor/editor.js
> Don't propagate command-Z in any case when the canvas has focus

- src/fontra/views/editor/editor.js
> Command-a functionality for select/deselect all points

- src/fontra/views/editor/editor.js
> Add select all/none to the the context menu

- src/fontra/views/editor/editor.js
Implements a feature from #240
> Shortcuts for tools issue247

- src/fontra/client/core/var-path.js
- src/fontra/views/editor/edit-tools-pen.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-draw-funcs.js
> [Pen tool] connect to other open path

- src/fontra/client/core/path-functions.js
- src/fontra/views/editor/scene-controller.js
I added a new option but for the implementation I will need much more time to understand what's going on. 
I leave a PR in case @justvanrossum wants to implement it or leave it for me for next week.
This fixes #268
> Add new option to the contextMenuItems

- src/fontra/client/core/context-menu.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
This should make #276 and #255 easier.
> Rework contextual menu

- src/fontra/client/core/glyph-controller.js
- src/fontra/views/editor/scene-draw-funcs.js
> Skip open contours when drawing the fill in edit mode

- .github/dependabot.yml
Configure `dependabot` updates also for `GitHub actions` and `npm` packages.
> Update `dependabot` config.

- src/fontra/client/core/path-functions.js
- src/fontra/client/core/var-path.js
- src/fontra/views/editor/edit-behavior.js
- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/scene-controller.js
- src/fontra/views/editor/scene-model.js
> Implement connecting two open paths and closing an open path by dragging a point

- src/fontra/client/core/path-hit-tester.js
- src/fontra/client/core/var-path.js
- test-js/test-path-hit-tester.js
This will make it easier to work with segments ("a contour as a sequence of segments" vs. "a contour as a sequence of points")
> Refactor path drawing: iterate over decomposed segments

- src/fontra/views/editor/edit-tools-pointer.js
- Clicking on a segment selects all points that make up the segment
- Double-clicking on a segment selects all points that make up the contour
- Dragging a segment works as if you're dragging the selected points
Additionally:
- The alt modifier is used to add or subtract from the current selection
| shiftKey | altKey | selection effect |
|---|---|---|
| false | false | clicked items become the selection |
| true | false | selected state of clicked items is inverted |
| false | true | clicked items are added to the selection |
| true | true | clicked items are subtracted from the selection | 
...and the same for rectangle select.
> Add segment-click-select, and use alt modifier

- src/fontra/client/core/path-functions.js
- src/fontra/client/core/var-path.js
- src/fontra/views/editor/edit-tools-pen.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
When clicking on a segment with the pen tool, insert a point. Implements part of #30.
To do:
> [pen tool] Implement insert point

- package-lock.json
- package.json
> Move `chai` and `mocha` to `devDependencies`. #288

- src/fontra/client/core/var-path.js
- test-js/test-var-path.js
Needed for more convenient Paste implementation, therefore relates to #260 and #75
> Add appendPath() method to VarPackedPath

- src/fontra/client/core/font-controller.js
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/path-functions.js
- src/fontra/client/core/utils.js
- src/fontra/client/core/var-path.js
- src/fontra/views/editor/editor.js
- Implement internal clipboard format (StaticGlyph as JSON)
- Implement Cut
- Take selection into account when copying and cutting
> Misc copy / cut work

- src/fontra/client/core/mouse-tracker.js
- src/fontra/client/core/path-functions.js
- src/fontra/views/editor/edit-tools-pen.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-draw-funcs.js
> [pen tool] Turn line into curve with alt-click 

- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/rectangle.js
> Draw a loud placeholder for missing component base glyphs

- src/fontra/client/core/utils.js
- src/fontra/views/editor/editor.js
> Safari copy/paste plain text to the clipboard

- src/fontra/client/core/utils.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
> Use local storage clipboard in Safari + HTTP context

- src/fontra/filesystem/projectmanager.py
- src/fontra/views/editor/editor.js
This fixes #301, and needs https://github.com/googlefonts/fontra-pak/pull/19
> Improve how fs paths are represented in the URL, and improve the document title

- src/fontra/client/core/ui-list.js
- src/fontra/client/core/utils.js
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/glyphs-search.js
Moving everything related to glyphs search to its own module so it can be reused. Needed for #319/#338
> Glyph search refactor

- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/visualization-layer-definitions.js
> Crosshair visualization layer

- src/fontra/views/editor/visualization-layer-definitions.js
> Add upm grid (when zoomed in more than 4 pixels per unit)

- src/fontra/client/core/ui-list.js
- src/fontra/client/css/ui-styling.css
- src/fontra/client/web-components/theme-support.js
- src/fontra/client/web-components/ui-list.js
- src/fontra/views/editor/editor.css
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/glyphs-search.js
Converts the `List` class to a web component.
TODO:
> UI List refactor

- src/fontra/client/core/ui-dialog.js
- src/fontra/client/css/ui-styling.css
- src/fontra/client/web-components/glyphs-search.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-model.js
This fixes #319.
This supersedes #338.
> Add new component

- src/fontra/backends/opentype.py
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
> Make sidebar visible/selected state persistent

- src/fontra/client/web-components/glyphs-search.js
- src/fontra/views/editor/editor.js
Add two sidebar short cuts: cmd-i for the info sidebar, cmd-f for the glyph search sidebar
> Add two sidebar short cuts: cmd-i and cmd-f

- src/fontra/client/core/font-controller.js
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/unlit.js
- src/fontra/client/web-components/dialog-overlay.js
- src/fontra/client/web-components/range-slider.js
- src/fontra/views/editor/editor.css
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
This fixes #399 
It also includes edit context refactoring so we can use the same machinery to also edit a variable glyph and not just an instance.
TODO:
> Edit source properties

- src/fontra/client/core/observable-object.js
- src/fontra/client/core/theme-settings.js
- src/fontra/client/core/utils.js
- src/fontra/client/web-components/designspace-location.js
- src/fontra/client/web-components/grouped-settings.js
- src/fontra/client/web-components/simple-settings.js
- src/fontra/views/editor/editor.js
- test-js/test-observable-object.js
Separate controller logic from model proxy, to avoid namespace clashes, and to have a clearer separation of concern.
> Observable object refactoring

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
- Use helper function
- Use ObservableController for data binding
(Accidentally unrelated: import cleanup in scene-controller.js)
> Source properties UI refactor

- src/fontra/client/core/unlit.js
- src/fontra/client/web-components/dialog-overlay.js
- src/fontra/views/editor/editor.js
Break up dialog in:
- setup
- run
This makes it easier to add custom content.
> Dialog refactor

- src/fontra/client/web-components/designspace-location.js
- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
- src/fontra/views/editor/scene-model.js
- src/fontra/views/editor/sidebar-designspace.js
- move designspace sidebar code to its own module
- use ObservableController for dataflow for better factorisation
> Refactor sidebar ds

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/sidebar-text-entry.js
Separating things better by using ObservableController for the data flow.
> Factor out text entry sidebar UI to its own module

- src/fontra/backends/designspace.py
- src/fontra/backends/opentype.py
- src/fontra/client/core/change-recorder.js
- src/fontra/client/core/classes.json
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/var-glyph.js
- src/fontra/core/classes.py
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/scene-controller.js
- src/fontra/views/editor/sidebar-designspace.js
- test-js/test-classes.js
- test-js/test-var-glyph.js
- test-py/test_font.py
- test-py/test_fonthandler.py
Layer names need to be unique, and layers need to be found by name. It made little sense for glyph.layers to be a list.
> Make glyph.layers a dict instead of a list

- src/fontra/client/core/context-menu.js
- src/fontra/client/web-components/dialog-overlay.js
> Restore focused/active element after context menu and dialog dismiss

- src/fontra/client/web-components/ui-list.js
> Use the correct container for pre-overscroll detection

- src/fontra/client/core/context-menu.js
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/web-components/ui-list.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/sidebar-designspace.js
Fixes #487.
Command arrow-up/arrow-down.
> Add context menu items and short cuts for going to previous/next source

- src/fontra/client/core/unlit.js
- src/fontra/client/core/utils.js
- src/fontra/client/web-components/reference-font.js
- src/fontra/client/web-components/ui-list.js
- src/fontra/views/editor/editor.js
> [reference viewer] allow multiple fonts to be dropped, select between them

- src/fontra/client/core/transform.js
From https://github.com/googlefonts/fontra/discussions/194
> Update transform.js with context in line 1 comment

- src/fontra/client/core/utils.js
- src/fontra/client/web-components/menu-panel.js
- src/fontra/views/editor/sidebar-designspace.js
> Implement status source field

- src/fontra/backends/designspace.py
- test-py/test_fonthandler.py
> Fix deleting layers in designspace backend

- src/fontra/views/editor/edit-behavior.js
> Make "floating" off-curve points move with the rest

- src/fontra/client/core/utils.js
- test-js/test-utils.js
Initial PR for the test cases of `utils.js`.
> Tests for utils

- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/editor.js
> Select only on-curve points when pasting, and double-clicking a contour

- src/fontra/backends/designspace.py
- test-py/test_font.py
- test-py/test_fonthandler.py
> [designspace] Improve source and layer names

- src/fontra/backends/designspace.py
- test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.support.crossbar/B_.glif
- test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.support/A_.glif
- test-py/test_backend_designspace.py
- test-py/test_font.py
Preparing for #528
- Fix writing of variable glyphs (with local axes)
- Better source names for variable glyphs (with local axes)
- Test glyph write round-tripping
> Designspace fixes

- src/fontra/client/web-components/reference-font.js
This PR fix #540 by showing a dialog listing the dropped files that are not supported.
> Show dialog with unsupported file list message.

- src/fontra/client/css/ui-styling.css
- src/fontra/views/editor/sidebar-selection-info.js
> Show character in addition to U+1234 value in info panel

- src/fontra/backends/designspace.py
- test-py/test_backend_designspace.py
- Refactor how DS sources and UFO layers are managed
- Implement creating new source UFO, layers, DS sources
> [designspace] Implement creating new DS sources, UFO layers and UFOs

- src/fontra/views/editor/editor.js
This is a preliminary fix for #551.
> Add confirmation dialog before adding component glyphs to the text string

- src/fontra/client/core/utils.js
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
- test-js/test-utils.js
Fixes #574.
I implemented the resizing in `editor.js`, all the other sidebar related functionality is implemented there, however I feel like the sidebar needs to be converted into a web component.
> Make sidebars resizable

- src/fontra/views/editor/editor.js
> Sidebar widths should be stored in localstorage

- src/fontra/__main__.py
- src/fontra/core/server.py
> Find a free localhost port when launched locally

- src/fontra/views/editor/editor.html
> Fix textarea grows more than 100%

- src/fontra/views/editor/editor.js
> Focus the cavas after clicking a tool

- src/fontra/client/core/path-hit-tester.js
- src/fontra/views/editor/edit-tools-power-ruler.js
> [ruler] take side bearings into account

- src/fontra/client/core/canvas-controller.js
- src/fontra/client/core/unlit.js
- src/fontra/client/core/utils.js
- src/fontra/views/editor/visualization-layers.js
Turn the "request update" pattern into a new helper func named `consolidateCalls()`, similar to `scheduleCalls()`, but without a delay.
> Request update refactor

- test-js/test-path-hit-tester.js
- test-js/test-support.js
> Add parametrize helper func, use it in path-hit tests

- src/fontra/client/core/rectangle.js
- test-js/test-rectangle.js
> Rectangle.js unit tests

- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/var-glyph.js
- src/fontra/views/editor/sidebar-designspace.js
> Make interpolation of components be lenient of incompatible location dicts

- src/fontra/client/core/font-controller.js
- src/fontra/client/core/task-pool.js
> Use a task pool to limit how many concurrent glyph requests we fire

- src/fontra/views/editor/editor.js
> Add component to all sources checkbox should remember its setting

- src/fontra/client/core/font-controller.js
> Also notify all glyphs that depend on the changed glyph

- src/fontra/views/editor/visualization-layer-definitions.js
- src/fontra/views/editor/visualization-layers.js
> Add option to show sidebearing for non-editing glyphs

- src/fontra/client/core/glyph-lines.js
- src/fontra/client/core/rectangle.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
- src/fontra/views/editor/scene-model.js
Moving some stuff from editor to scene controller
> More scene refactoring

- src/fontra/client/core/utils.js
- src/fontra/views/editor/edit-behavior.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
- src/fontra/views/editor/scene-model.js
- src/fontra/views/editor/sidebar-selection-info.js
- src/fontra/views/editor/visualization-layer-definitions.js
Also renames some selection stuff.
> [vis layer] Show coordinates/origins of selected nodes and components

- src/fontra/views/editor/sidebar-selection-info.js
> Only respond to positionedLines change if we didn't have an instance yet

- src/fontra/client/core/mouse-tracker.js
- src/fontra/client/core/queue-iterator.js
- src/fontra/client/core/ui-form.js
- src/fontra/client/core/utils.js
- src/fontra/views/editor/scene-controller.js
> Don't error when editing quickly on a slow connection, but wait a bit for the previous edit to be done

- src/fontra/client/web-components/reference-font.js
- src/fontra/views/editor/editor.css
> Reference font dialog should not overflow

- src/fontra/client/web-components/modal-dialog.js
> Keep canvas focus after dialog

- src/fontra/client/core/ui-form.js
- src/fontra/client/web-components/range-slider.js
> Keep focus on canvas while moving sliders

- src/fontra/views/editor/editor.js
> Reset autoViewBox on zoom in/out/fit

- src/fontra/views/editor/editor.js
> Take selected source index from scene settings instead of from the instance

- src/fontra/client/web-components/ui-list.js
- src/fontra/views/editor/panel-designspace-navigation.js
> Keep the scroll position when resetting the source list contents

- src/fontra/client/core/unlit.js
- src/fontra/client/tabler-icons/LICENSE.txt
- src/fontra/client/tabler-icons/README.md
- src/fontra/client/tabler-icons/refresh.svg
- src/fontra/client/web-components/icon-button.js
- src/fontra/client/web-components/inline-svg.js
- src/fontra/core/server.py
- src/fontra/views/editor/panel-designspace-navigation.js
This also adds an "icon-button" web components. It also premieres the use of a "tabler" icon (#698)
This fixes #732.
> Add "reset all axes" button to designspace navigation

- src/fontra/client/css/core.css
- src/fontra/client/web-components/modal-dialog.js
- src/fontra/client/web-components/range-slider.js
- src/fontra/client/web-components/reference-font.js
- src/fontra/client/web-components/ui-form.js
Some themed styling broke during recent refactoring.
> Fix info styling

- src/fontra/backends/designspace.py
- src/fontra/core/clipboard.py
- test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/varcotest2.glif
- test-py/test_backend_designspace.py
- test-py/test_font.py
This fixes #759 and fixes #530.
> Local designspace fixes

- src/fontra/client/web-components/ui-list.js
> Make sure that cell containers use the same CSS as header cells

- src/fontra/backends/designspace.py
> Fix AttributeError with external new glyphs

- src/fontra/views/editor/editor.css
- src/fontra/views/editor/panel-designspace-navigation.js
> Fix resize regression

- src/fontra/client/tabler-icons/circle-dot-filled.svg
- src/fontra/client/tabler-icons/circle-dot.svg
- src/fontra/client/tabler-icons/circle-dotted.svg
- src/fontra/client/tabler-icons/eye-closed.svg
- src/fontra/client/tabler-icons/eye.svg
- src/fontra/views/editor/panel-designspace-navigation.js
Work in progress. It will fix #767.
>  Styling + behavior of checkboxes in the source list

- src/fontra/views/editor/panel-designspace-navigation.js
> Refactor icon cells into one func; make icon cell update its own state

- src/fontra/client/web-components/menu-panel.js
> [context-menu] Choose item when release mouse after control-click and drag.

- src/fontra/client/web-components/designspace-location.js
- src/fontra/client/web-components/range-slider.js
- The slider does not need a name property
- Emit dragBegin/dragEnd flags in callback event
This is in preparation of using the range slider in the info panel.
> Range slider updates

- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/var-model.js
- src/fontra/client/tabler-icons/bug.svg
- src/fontra/client/web-components/ui-list.js
- src/fontra/views/editor/panel-designspace-navigation.js
> Add interpolation status column to the source list

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/sidebar.js
> Sidebar width now default to minimum, should be wider, as before

- src/fontra/views/editor/editor.css
> tools now in absolute position and sidebar-tab now above the tools

- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/utils.js
- src/fontra/client/tabler-icons/exclamation-circle.svg
- src/fontra/views/editor/panel-designspace-navigation.js
> Detect non unique source locations and show them as interpolation errors in the sources list

- .pre-commit-config.yaml
- src/fontra/filesystem/landing.html
- src/fontra/views/editor/cjk-design-frame.js
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/panel-selection-info.js
So we consistently use 3.0.3 everywhere.
> [pre-commit] Update prettier

- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
Fixes #401.
(I need this for #850)
> Prevent negative advance

- src/fontra/client/web-components/range-slider.js
> Ensure we don't emit dragEnd multiple times

- src/fontra/client/core/fit-cubic.js
- src/fontra/client/core/path-functions.js
- src/fontra/client/core/utils.js
- src/fontra/client/core/var-path.js
- test-js/test-fit-cubic.js
This fixes #451 and fixes #438.
TODO:
> Implement better point deletion

- src/fontra/views/editor/edit-tools-power-ruler.js
> Make double-click hide the ruler

- src/fontra/client/core/glyph-lines.js
For example this allows us to write /Å.alt as a shortcut for /Aring.alt in the text entry field.
This fixes #715.
> Allow 'pseudo' glyph names, made of a single character + an extension

- src/fontra/client/core/path-functions.js
- src/fontra/views/editor/edit-tools-pen.js
> Misc insert point/handles fixes

- src/fontra/client/core/font-controller.js
- src/fontra/client/core/lru-cache.js
- src/fontra/views/editor/scene-model.js
> Show loader spinner when glyphs need loading from the server

- src/fontra/client/core/html-utils.js
- src/fontra/client/core/utils.js
- src/fontra/client/web-components/designspace-location.js
- src/fontra/client/web-components/glyphs-search.js
- src/fontra/client/web-components/grouped-settings.js
- src/fontra/client/web-components/icon-button.js
- src/fontra/client/web-components/inline-svg.js
- src/fontra/client/web-components/menu-panel.js
- src/fontra/client/web-components/modal-dialog.js
- src/fontra/client/web-components/simple-settings.js
- src/fontra/client/web-components/ui-form.js
- src/fontra/client/web-components/ui-list.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/panel-glyph-search.js
- src/fontra/views/editor/panel-reference-font.js
- src/fontra/views/editor/panel-selection-info.js
- src/fontra/views/editor/panel-text-entry.js
- src/fontra/views/editor/panel-user-settings.js
- src/fontra/views/editor/panel.js
- src/fontra/views/editor/sidebar.js
> Unlit.js -> html-utils.js, move htmlToElement to html-utils

- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
> Fix several display update issues around deleting sources

- src/fontra/views/editor/edit-tools-pointer.js
> Resepect modifier keys when double-clicking a contour

- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/scene-controller.js
> Fix error when trying to draw in brand new glyph

- src/fontra/views/editor/panel-designspace-navigation.js
> Reset autoViewBox when pulling axis sliders

- src/fontra/client/core/changes.js
- src/fontra/client/core/glyph-glif.js
- src/fontra/core/classes.py
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
This fixes #882 and fixes #420.
> Whole glyph copy paste

- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-glyph-search.js
- src/fontra/views/editor/scene-controller.js
- Implement general data change subscription mechanism
- Move some special cases to change listeners
> Edit change refactor

- src/fontra/backends/designspace.py
- src/fontra/client/core/font-controller.js
- src/fontra/views/editor/editor.js
- test-py/test_backend_designspace.py
> Implement delete glyph

- src/fontra/client/core/font-controller.js
- src/fontra/views/editor/editor.js
> Make undo work for glyph deletion and glyph creation

- src/fontra/client/core/font-controller.js
Properly track and apply changes that affect the glyph set itself (deleted/added glyphs).
This fixes #944.
> Fix misc. undo/redo delelete glyph / create glyph issues

- src/fontra/client/core/font-controller.js
- src/fontra/views/editor/editor.js
> Implement cut glyph in select mode

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/panel-reference-font.js
- src/fontra/views/editor/panel-selection-info.js
- src/fontra/views/editor/panel-text-entry.js
- src/fontra/views/editor/panel.js
> Get rid of attach()

- src/fontra/views/editor/editor.js
Show "Delete glyph" in select mode and "Delete selection" in edit mode. This fixes #953.
> Make Delete context menu item title dynamic

- package-lock.json
- package.json
- src/fontra/client/core/utils.js
- src/fontra/core/urlfragment.py
- src/fontra/views/editor/editor.js
- test-common/url-fragment-test-data.json
- test-js/test-changes.js
- test-js/test-support.js
- test-js/test-utils.js
- test-py/test_urlfragment.py
> Change the URL format to use fragment, compression and base64

- src/fontra/client/core/html-utils.js
- src/fontra/client/web-components/range-slider.js
> Delete lit dependency on range-slider

- src/fontra/views/editor/sidebar.js
> Restore sidebar visibility before the panels

- src/fontra/views/editor/editor.js
> Force-sync location to refresh selected source index

- src/fontra/views/editor/editor.js
> Wait for plugins to load if the stored panel name is not builtin

- src/fontra/client/web-components/range-slider.js
Includes fixes for the revert of #952.
> Delete lit dependency of range slider

- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
> Don't reset editing layers when switching glyphs

- src/fontra/client/web-components/designspace-location.js
- src/fontra/client/web-components/range-slider.js
Implements #193.
It's done, but I left test values for testing.
> Implement discrete values for range-slider

- requirements.txt
- src/fontra/backends/fontra.py
- src/fontra/core/classes.py
- src/fontra/core/path.py
- src/fontra/core/remote.py
- src/fontra/core/serverutils.py
- test-py/test_classes.py
- test-py/test_font.py
- test-py/test_path_io.py
cattrs offers some more flexibility, esp. one can more easily customize how objects are "unstructured", via hooks.
> Switch from dacite to cattrs for object structuring / destructuring

- src/fontra/client/web-components/add-remove-buttons.js
> Rewrite add-remove-buttons with html.UnlitElement

- package-lock.json
- package.json
- src/fontra/client/core/html-utils.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/panel-glyph-search.js
- src/fontra/views/editor/panel-reference-font.js
- src/fontra/views/editor/panel-selection-info.js
- src/fontra/views/editor/panel-text-entry.js
- src/fontra/views/editor/panel-user-settings.js
> Delete lit dependency

- src/fontra/views/editor/panel-text-entry.js
> Focus only when focus attribute is true when text entry panel is toggled

- scripts/rollup_build_hook.py
> Delete the third party javascript folder when pip install -e

- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/editor.js
> Move double-click component handler to editor.js

- src/fontra/__main__.py
- src/fontra/backends/__init__.py
- src/fontra/backends/copy.py
- src/fontra/backends/designspace.py
- src/fontra/backends/fontra.py
- src/fontra/backends/opentype.py
- src/fontra/core/fonthandler.py
- src/fontra/core/protocols.py
- src/fontra/core/remote.py
- src/fontra/core/server.py
- src/fontra/filesystem/projectmanager.py
- test-py/test_add_version_token.py
- test-py/test_fonthandler.py
- test-py/test_protocols.py
Add initial backend protocols, apply them, test them, and add some more typing
> Add backend protocols

- src/fontra/client/web-components/ui-form.js
> Glyph width increment 10 by 10 if shift pressed

- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-model.js
This fixes #1024
- Add getGlyphsUsedBy backend API
- Add general backend info method, that exposes info about optional features
- add a context menu item "Find glyphs that use this glyph"
> Implement "glyphs used by glyph"

- src/fontra/client/core/font-controller.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/panel-glyph-search.js
> Delete sidebar init methods in editor.js

- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
> Don't error on setting advance width for empty glyph 

- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-selection-info.js
- src/fontra/views/editor/scene-controller.js
This implements part of #1050.
> Expose read-only mode, and make sure the user is informed when attempting to edit a read-only font

- src/fontra/views/editor/editor.js
> Add shortcut command-e to toggle the edit state of all sources

- src/fontra/client/web-components/modal-dialog.js
- src/fontra/client/web-components/plugin-manager.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/panel-reference-font.js
- src/fontra/views/editor/scene-controller.js
> Add message() to modal-dialog

- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
> Implementation of X/Y component transformation fields

- src/fontra/backends/fontra.py
- test-py/test_backends_fontra.py
> Implement and test deleteGlyph()

- requirements-dev.txt
- requirements.txt
> Manual bump dependencies, due to pytest 8 vs pytest-asyncio incompatibility

- .pre-commit-config.yaml
- src/fontra/client/core/glyph-lines.js
- src/fontra/client/core/utils.js
- src/fontra/core/glyphnames.py
- test-py/test_glyphnames.py
> Issue 1093 olli

- src/fontra/client/core/glyph-lines.js
- src/fontra/client/core/server-utils.js
- src/fontra/core/glyphnames.py
- src/fontra/core/serverutils.py
- test-py/test_glyphnames.py
> refactoring getUnicodeFromGlyphName to getCodePointFromGlyphName

- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
Fixes #1109 
I am not able to get and set the value before, but I guess it would require a more. For now, this is a fix with an info message and after that you can undo you change. What do you think @justvanrossum
> Bug 1109 metrics fields

- src/fontra/client/css/tooltip.css
> Fix: Tooltip in bottom position renders misaligned

- src/fontra/client/core/utils.js
- src/fontra/client/css/tooltip.css
- src/fontra/views/editor/editor.css
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/sidebar.js
- test-js/test-utils.js
Fixes #1110 
I added the tooltip attributes, but they actually breaks the current functionality of the UI. 
@fatih-erikli @fabiocaccamo Do you have an idea, why this is the case?
> Added tooltips attributes

- src/fontra/views/editor/edit-tools-pen.js
> Implement shift-constrain for pen tool add point

- src/fontra/client/css/tooltip.css
- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
> Add buttons to reset component axis values and transformation

- src/fontra/views/editor/editor.css
- src/fontra/views/editor/editor.html
- make menu bar participate in "cleanable-overlay", meaning it will disappear when pressing the space bar
- tweak menu bar appearance: use small shadow instead of solid border
> Menu tweaks

- src/fontra/views/editor/editor.css
> Fix height of sidebars

- src/fontra/workflow/command.py
- src/fontra/workflow/workflow.py
- test-py/test_workflow.py
> Allow workflows to be chained

- pyproject.toml
- src/fontra/backends/workflow.py
- src/fontra/workflow/command.py
- src/fontra/workflow/workflow.py
- test-py/data/mutatorsans/MutatorSans_workflow.yaml
- test-py/test_backends_workflow.py
- test-py/test_workflow.py
> Workflow backend

- src/fontra/workflow/actions.py
- test-py/data/workflow/output-rename-axes.fontra/font-data.json
- test-py/data/workflow/output-rename-axes.fontra/glyph-info.csv
- test-py/data/workflow/output-rename-axes.fontra/glyphs/A^1.json
- test-py/test_workflow.py
> Add rename-axes action

- src/fontra/client/web-components/ui-form.js
> Bugfix: UI issues with ui-form-label

- src/fontra/client/web-components/modal-dialog.js
> Bugfix: UI issue with edit local axes

- src/fontra/workflow/actions.py
- test-py/data/workflow/output-drop-axis-mapping-noop.fontra/font-data.json
- test-py/data/workflow/output-drop-axis-mapping-noop.fontra/glyph-info.csv
- test-py/data/workflow/output-drop-axis-mapping-noop.fontra/glyphs/A^1.json
- test-py/data/workflow/output-drop-axis-mapping.fontra/font-data.json
- test-py/data/workflow/output-drop-axis-mapping.fontra/glyph-info.csv
- test-py/data/workflow/output-drop-axis-mapping.fontra/glyphs/A^1.json
- test-py/test_workflow.py
> Implement drop-axis-mapping action

- src/fontra/views/editor/visualization-layer-definitions.js
Fixes #1117 and fixes #1157.
Reordering like requested in #1116 is a different task.
> Indexing components and contours

- src/fontra/backends/designspace.py
- src/fontra/backends/ufo_utils.py
- src/fontra/client/core/cmap.js
- src/fontra/client/core/font-controller.js
- src/fontra/client/core/glyph-glif.js
- src/fontra/client/core/utils.js
- src/fontra/client/web-components/glyphs-search.js
- src/fontra/core/clipboard.py
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-selection-info.js
- test-js/test-utils.js
> Refactoring 'unicode' to 'codePoint'

- src/fontra/client/web-components/ui-form.js
> Fixing scroll issue

- src/fontra/workflow/actions.py
- test-py/data/workflow/output-adjust-axes-no-mapping.fontra/font-data.json
- test-py/data/workflow/output-adjust-axes-no-mapping.fontra/glyph-info.csv
- test-py/data/workflow/output-adjust-axes-no-mapping.fontra/glyphs/A^1.json
- test-py/data/workflow/output-adjust-axes.fontra/font-data.json
- test-py/data/workflow/output-adjust-axes.fontra/glyph-info.csv
- test-py/data/workflow/output-adjust-axes.fontra/glyphs/A^1.json
- test-py/test_workflow.py
> Implement adjust-axes action

- src/fontra/backends/copy.py
- src/fontra/backends/designspace.py
- src/fontra/backends/fontra.py
- src/fontra/backends/opentype.py
- src/fontra/backends/workflow.py
- src/fontra/core/fonthandler.py
- src/fontra/core/protocols.py
- src/fontra/core/server.py
- src/fontra/filesystem/projectmanager.py
- src/fontra/workflow/actions.py
- src/fontra/workflow/merger.py
- test-py/test_backends_fontra.py
- test-py/test_font.py
- test-py/test_fonthandler.py
This will also affect fontra-rcjk, fontra-glyphs and fontra-pak.
> backend protocol change: close() becomes async aclose()

- src/fontra/views/editor/visualization-layer-definitions.js
> Safari issue: index label

- src/fontra/backends/designspace.py
- src/fontra/backends/filewatcher.py
- src/fontra/core/fonthandler.py
- src/fontra/core/protocols.py
- test-py/test_filewatcher.py
- Add a new filewatcher module, a layer on top of watchfiles, that makes it easier to watch a changing set of paths
- Refactor how FontHandler and backends communicate external changes
> Refactor "file watching"

- src/fontra/workflow/actions.py
- test-py/data/workflow/input-set-names.fontra/font-data.json
- test-py/data/workflow/input-set-names.fontra/glyph-info.csv
- test-py/data/workflow/output-set-names.fontra/font-data.json
- test-py/data/workflow/output-set-names.fontra/glyph-info.csv
- test-py/test_workflow.py
> Add set-names action

- src/fontra/workflow/actions.py
- test-py/data/workflow/input-drop-unreachable-glyphs.fontra/font-data.json
- test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyph-info.csv
- test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyphs/A^1.json
- test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyphs/Adieresis^1.json
- test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyphs/dieresis.json
- test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyphs/dot.json
- test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/font-data.json
- test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyph-info.csv
- test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyphs/A^1.json
- test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyphs/Adieresis^1.json
- test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyphs/dieresis.json
- test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyphs/dot.json
- test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/font-data.json
- test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/glyph-info.csv
- test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/glyphs/A^1.json
- test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/glyphs/Adieresis^1.json
- test-py/test_workflow.py
> Implement drop-unreachable-glyphs action

- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
Fixes #1133
Hi @justvanrossum,
I am kind of lost. This task should be very easy, but it turns out it's more complex then I thought. 
My first idea was, it should be possible to style the input number to display only one decimal place via CSS when it's active or not active. It turns out, this is not possible. Then I tried to find a javascript solution, please see the code.
Would be great to get you feedback before I spend/loose more time on it. Thanks
> UI improvements for sidebearing value

- src/fontra/workflow/actions.py
- test-py/data/workflow/output-subset-axes.fontra/font-data.json
- test-py/data/workflow/output-subset-axes.fontra/glyph-info.csv
- test-py/data/workflow/output-subset-axes.fontra/glyphs/A^1.json
- test-py/data/workflow/output-subset-axes.fontra/glyphs/B^1.json
- test-py/test_workflow.py
> Implement axis subsetting

- src/fontra/workflow/actions.py
This is just a simplification of code. I was hoping for a speedup, but I can't measure any significant difference.
> Simplify instantiation: no need to use the pen protocol

- src/fontra/core/instancer.py
- src/fontra/workflow/actions.py
- test-py/data/workflow/input-variable-composites.fontra/glyphs/uni4FFC^G3.json
- test-py/data/workflow/output-decompose-variable-composites.fontra/glyphs/uni4FFC^G3.json
- test-py/data/workflow/output-subset-by-development-status-no.fontra/font-data.json
- test-py/data/workflow/output-subset-by-development-status-no.fontra/glyph-info.csv
- test-py/data/workflow/output-subset-by-development-status-yes.fontra/font-data.json
- test-py/data/workflow/output-subset-by-development-status-yes.fontra/glyph-info.csv
- test-py/data/workflow/output-subset-by-development-status-yes.fontra/glyphs/uni4FFC^G3.json
- test-py/test_workflow.py
This fixes #1262.
This also implements a "drop-shapes" action, that clears all paths and components.
> Implement subset-by-development-status action

- src/fontra/views/editor/edit-tools-pen.js
Instead of cleverly propagate change objects through all layers, properly execute each change in each layer, and record the result. Apart from fixing the multi-source connect-to-other-contour and close-contour bugs, this is also a simplification. Needs a more testing.
This fixes #1138 and fixes #1234.
> Change how multi-source pen tool works

- package-lock.json
- package.json
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/glyph-glif.js
- src/fontra/client/core/transform.js
- src/fontra/client/core/utils.js
- src/fontra/views/editor/edit-behavior.js
- src/fontra/views/editor/panel-transformation.js
- src/fontra/views/editor/visualization-layer-definitions.js
- test-js/test-transform.js
> Issue 1264 refactor affine

- src/fontra/client/core/transform.js
- src/fontra/client/core/var-glyph.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-selection-info.js
- test-js/test-glyph-controller.js
- test-js/test-transform.js
- test-js/test-var-glyph.js
> Refactor use getDecomposedIdentity

- src/fontra/client/core/glyph-controller.js
- src/fontra/views/editor/panel-transformation.js
- test-js/test-glyph-controller.js
> Adding method getSelectionBounds + unittest

- src/fontra/client/core/font-controller.js
Fix regression caused by #1279.
> Fix single-ufo axes

- src/fontra/client/css/core.css
- src/fontra/client/web-components/ui-form.js
> Fix input text size in Safari

- src/fontra/backends/designspace.py
- src/fontra/client/core/classes.json
- src/fontra/core/classes.py
- src/fontra/core/clipboard.py
- src/fontra/workflow/actions.py
- test-common/fonts/MutatorSans.fontra/glyphs/E^1.json
- test-py/test_backends_designspace.py
- test-py/test_backends_fontra.py
- test-py/test_fonthandler.py
- test-py/test_workflow.py
> [designspace] implement reading and writing of anchors

- src/fontra/views/editor/editor.js
> spacebar down for hand tool + cleanSceneView

- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/var-glyph.js
- src/fontra/client/web-components/modal-dialog.js
- src/fontra/views/editor/edit-behavior.js
- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-model.js
- src/fontra/views/editor/visualization-layer-definitions.js
- test-js/test-glyph-controller.js
- test-js/test-var-glyph.js
> Adding support for anchors

- README.md
- src/fontra/client/core/glyph-controller.js
- src/fontra/views/editor/panel-transformation.js
- test-js/test-glyph-controller.js
> Include anchors to transformation panel tools

- src/fontra/backends/copy.py
- src/fontra/backends/null.py
- src/fontra/workflow/actions.py
- src/fontra/workflow/workflow.py
- test-py/data/mutatorsans/MutatorSans_workflow.yaml
- test-py/test_backends_null.py
- test-py/test_workflow.py
> [fontra-workflow] Major refactoring, renaming

- src/fontra/views/editor/editor.js
> Update documentation link

- src/fontra/views/editor/visualization-layer-definitions.js
> Bugfix anchor with visualization layer

- src/fontra/client/core/utils.js
- src/fontra/views/editor/visualization-layer-definitions.js
- test-js/test-utils.js
Fixes #926 
I am very sorry for the confusion.
Base on the feedback stored here #1342
> Adding status color + fix rgbaToCSS

- src/fontra/views/editor/scene-model.js
> Prevent out-of-order drawing by cancelling updates in-progress

- src/fontra/views/editor/visualization-layer-definitions.js
> Top of the color bar at CJK designframe bottom value, relative to the UPM

- src/fontra/views/editor/visualization-layer-definitions.js
Fixes #1356 
https://github.com/googlefonts/fontra/assets/21055547/a1e45bae-7f7f-4926-90b2-3e47d6ad77b9
> Fix status color issue with newly created glyph or layer

- src/fontra/client/tabler-icons/menu-2.svg
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
> Make Font axes UI switchable between User and Source location

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
> Add hidden axes toggle

- src/fontra/client/core/discrete-variation-model.js
- src/fontra/client/core/font-controller.js
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/multiple-axis-mapping.js
- src/fontra/client/core/var-model.js
- src/fontra/client/web-components/menu-panel.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
- test-js/test-multiple-axis-mapping.js
- test-js/test-var-model.js
> Implement and apply the avar-2 multiple axis mapping algorithm

- src/fontra/client/web-components/designspace-location.js
- src/fontra/client/web-components/range-slider.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
> Add "phantom" sliders to show the effective location

- src/fontra/client/web-components/designspace-location.js
- src/fontra/client/web-components/range-slider.js
> Refine 'phantom' range slider

- src/fontra/backends/opentype.py
- test-py/test_backends_opentype.py
> Read avar2 mapping from ttf/otf

- src/fontra/client/core/font-controller.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/scene-controller.js
- fix MultipleAxisMapping behavior on hot reload
- add reloadEverything() method to EditorController
> [avar-2] Fix MultipleAxisMapping behavior on hot reload

- src/fontra/views/editor/editor.js
> Bugfix command A

- src/fontra/client/core/glyph-controller.js
- src/fontra/core/instancer.py
- test-py/data/workflow/input-axis-value-inheritance.fontra/font-data.json
- test-py/data/workflow/input-axis-value-inheritance.fontra/glyph-info.csv
- test-py/data/workflow/input-axis-value-inheritance.fontra/glyphs/A^1.json
- test-py/data/workflow/input-axis-value-inheritance.fontra/glyphs/B^1.json
- test-py/data/workflow/input-axis-value-inheritance.fontra/glyphs/C^1.json
- test-py/data/workflow/output-axis-value-inheritance.fontra/font-data.json
- test-py/data/workflow/output-axis-value-inheritance.fontra/glyph-info.csv
- test-py/data/workflow/output-axis-value-inheritance.fontra/glyphs/A^1.json
- test-py/data/workflow/output-axis-value-inheritance.fontra/glyphs/B^1.json
- test-py/data/workflow/output-axis-value-inheritance.fontra/glyphs/C^1.json
- test-py/test_workflow.py
This fixes #829.
WIP: needs test data and more testing.
> Component hierarchy: only let font axis values be inherited, and not glyph axis values

- src/fontra/backends/designspace.py
- src/fontra/backends/opentype.py
- src/fontra/client/core/classes.json
- src/fontra/client/core/cross-axis-mapping.js
- src/fontra/client/core/font-controller.js
- src/fontra/core/classes.py
- src/fontra/views/editor/panel-designspace-navigation.js
- src/fontra/views/editor/scene-controller.js
- test-js/test-multiple-axis-mapping.js
- test-py/test_backends_designspace.py
- test-py/test_backends_opentype.py
> Rename Multiple Axis Mapping to Cross-Axis Mapping

- src/fontra/backends/opentype.py
Extract glyph locations from VARC VarStore, so we build sources at the right locations.
> [VARC] Extract glyph locations from VARC VarStore

- src/fontra/views/editor/editor.js
- src/fontra/views/editor/visualization-layer-definitions.js
> Show guidelines: on default + when adding a new guideline

- src/fontra/backends/designspace.py
We need unique AND persistent keys for our font sources dict.
Needed for #1424.
> [designspace] Don't touch ds source.name attrs if they are unique, but do make them unique if they are not

- src/fontra/client/core/glyph-controller.js
> Fix caching issue: some cached items were never invalidated

- src/fontra/views/fontinfo/panel-axes.js
> Ensure element IDs are unique

- src/fontra/views/fontinfo/panel-sources.js
> [sources panel] Create random source identifier key

- src/fontra/client/core/localization.js
- src/fontra/views/editor/cjk-design-frame.js
- src/fontra/views/editor/edit-tools-power-ruler.js
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-reference-font.js
- src/fontra/views/editor/panel-user-settings.js
- src/fontra/views/editor/visualization-layer-definitions.js
> [localization] Ensure language file has loaded before starting UI

- src/fontra/client/core/cross-axis-mapping.js
- test-js/test-cross-axis-mapping.js
- test-py/data/avar2/DemoAvar2-NLI.designspace
> Fix interpretation of self-mapping axes; fix .designspace

- src/fontra/backends/designspace.py
- src/fontra/backends/opentype.py
- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/editor.js
- test-py/data/mutatorsans/MutatorSans.designspace
- test-py/test_backends_copy.py
- test-py/test_backends_designspace.py
- test-py/test_font.py
> [designspace] Support writing of font sources, vertical metrics

- src/fontra/backends/designspace.py
- test-py/test_backends_designspace.py
> Write .designspace file after we add the first implicit source

- src/fontra/backends/designspace.py
- test-py/test_backends_designspace.py
> [designspace] Fix font info writing in the absense of sources

- src/fontra/core/instancer.py
- src/fontra/workflow/actions/glyph.py
- src/fontra/workflow/actions/misc.py
- src/fontra/workflow/actions/subset.py
- test-py/data/workflow/input-interpolation-fail.fontra/font-data.json
- test-py/data/workflow/input-interpolation-fail.fontra/glyph-info.csv
- test-py/data/workflow/input-interpolation-fail.fontra/glyphs/A^1.json
- test-py/data/workflow/output-check-interpolation-no-fail.fontra/font-data.json
- test-py/data/workflow/output-check-interpolation-no-fail.fontra/glyph-info.csv
- test-py/data/workflow/output-check-interpolation-no-fail.fontra/glyphs/A^1.json
- test-py/data/workflow/output-interpolation-fail.fontra/font-data.json
- test-py/data/workflow/output-interpolation-fail.fontra/glyph-info.csv
- test-py/data/workflow/output-interpolation-fail.fontra/glyphs/A^1.json
- test-py/test_workflow.py
> [fontra-workflow] deal more gracefully with interpolation errors

- src/fontra/workflow/actions/axes.py
- test-py/test_workflow.py
This is necessary preparation for #1474.
> [fontra-workflow] Refactor axis mapping slicing

- src/fontra/client/core/discrete-variation-model.js
- src/fontra/client/core/font-sources-instancer.js
- src/fontra/client/core/glyph-controller.js
Some refactoring / cleanup for the DiscreteVariationModel.
I will port this code to Python and want to keep it similar.
> Discrete var model cleanup

- test-js/test-discrete-variation-model.js
> Unit tests for DiscreteVariationModel

- src/fontra/client/core/discrete-variation-model.js
- src/fontra/client/core/var-model.js
- src/fontra/core/discretevariationmodel.py
- src/fontra/core/varutils.py
- test-js/test-discrete-variation-model.js
- test-py/test_discretevariationmodel.py
- test-py/test_varutils.py
So we can support discrete axes in fontra-workflow.
> Port DiscreteVariationModel to Python

- src/fontra/backends/copy.py
- src/fontra/backends/designspace.py
- src/fontra/backends/fontra.py
- src/fontra/backends/null.py
- src/fontra/backends/opentype.py
- src/fontra/backends/workflow.py
- src/fontra/client/core/classes.json
- src/fontra/core/classes.py
- src/fontra/core/protocols.py
- src/fontra/workflow/actions/base.py
- src/fontra/workflow/merger.py
- test-py/test_backends_designspace.py
This fixes #1502.
- Kerning type definition
- getKerning/putKerning backend protocol additions
- .designspace/.ufo kerning read/write
- .fontra kerning read/write in exciting new .csv format
> Kerning plumbing

- src/fontra/views/editor/edit-tools-pointer.js
> Bugfix resize bounds: if selection is only one point

- src/fontra/views/editor/edit-tools-pointer.js
> Fix: Bounds Resize doesn't reset hover state

- requirements.txt
- test-py/test_workflow.py
> Bump ufomerge and fonttools

- src/fontra/client/core/font-sources-instancer.js
- src/fontra/client/core/glyph-controller.js
- src/fontra/client/core/utils.js
- src/fontra/client/core/var-glyph.js
- test-js/test-glyph-controller.js
Fixes #1525 
Fix guideline issue with normalizeGuidelines + update unittest
> Bugfix: Guideline with coordinate at zero is not selectable

- src/fontra/workflow/features.py
- test-py/data/workflow/output-add-features.fontra/features.txt
- test-py/data/workflow/output-generate-palt-vpal-feature.fontra/features.txt
Work around https://github.com/googlefonts/ufomerge/issues/24
> Ensure that .fea inputs end with a newline

- src/fontra/backends/designspace.py
- src/fontra/backends/opentype.py
- src/fontra/workflow/actions/base.py
- src/fontra/workflow/actions/glyph.py
> Remove local tuplifyLocation funcs, replace with central varutils.locationToTuple

- src/fontra/views/editor/edit-tools-shape.js
> Code quality: use model.shapeToolCtrlKey instead of model.event.ctrlKey

- pyproject.toml
- requirements.txt
- src/fontra/client/core/server-utils.js
- src/fontra/client/web-components/glyph-cell.js
- src/fontra/core/serverutils.py
- src/fontra/core/unicode.py
- src/fontra/views/editor/panel-related-glyphs.js
- src/fontra/views/editor/visualization-layer-definitions.js
- test-py/test_unicode.py
> [related glyphs] Add section for unicode decomposition relationships

- src/fontra/views/editor/edit-tools-pointer.js
> Improve UX of interactive resize tool

- src/fontra/views/editor/scene-model.js
> Fix point selection for points that overlap a segment

- src/fontra/client/core/classes.json
- src/fontra/client/core/var-path.js
- src/fontra/core/path.py
- test-js/test-change-recorder.js
- test-js/test-path-functions.js
- test-js/test-var-glyph.js
- test-js/test-var-path.js
- test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/A_.glif
- test-py/test_path.py
> Allow additional / arbitrary point attributes

- src/fontra/views/editor/edit-tools-pointer.js
- src/fontra/views/editor/scene-controller.js
> Hide transform selection tool if pointer-tool is not selected

- src/fontra/views/editor/scene-controller.js
> Rename callbacks with pattern doXxxxYyyy()

- src/fontra/client/core/classes.js
- src/fontra/client/core/var-glyph.js
- src/fontra/views/editor/edit-tools-knife.js
Clean up dict-comprehension-like code with mapObjectValues().
> Use mapObjectValues() helper func from utils.js wherever useful

- src/fontra/client/lang/en.json
- src/fontra/client/lang/zh-CN.json
- src/fontra/views/editor/panel-related-glyphs.js
> Make use of translation key: "sidebar.related-glyphs"

- src/fontra/client/core/utils.js
- src/fontra/views/editor/editor.js
> Show dialog message if URL is malformed.

- src/fontra/workflow/command.py
- src/fontra/workflow/workflow.py
- test-py/test_workflow.py
I have a use case for a templating feature for workflow yaml files: I need to build multiple fonts with subtle different inputs. This adds a `--substitute key:value` (multiple) argument to `fontra-workflow`, which allows strings that contain python-style `"aaa{key}bbb"` formatting. `{key}` would be substituted by `value`.
> Add templating feature to yaml file

- src/fontra/client/core/glyph-controller.js
- src/fontra/views/editor/edit-tools-pointer.js
- test-js/test-glyph-controller.js
> Bugfix: missing resize handles for one selected component

- src/fontra/client/core/var-path.js
- test-js/test-var-path.js
> Fix bug in path.getBounds()

- src/fontra/views/editor/editor.js
> Bugfix: select-next-source

- src/fontra/views/applicationsettings/applicationsettings.js
- src/fontra/views/applicationsettings/panel-server-info.js
- src/fontra/views/editor/editor.js
> Migrate server info to application settings

- src/fontra/client/lang/fr.js
> updated some french translation

- src/fontra/views/editor/editor.js
> Make use of modulo for doSelectPreviousNextSource

- src/fontra/views/fontinfo/panel-sources.js
> Fix issue with variable 'value' goes in loop

- CHANGELOG.md
This is just the first draft of a change log.
Rendered: https://github.com/googlefonts/fontra/blob/issue-1748-add-change-log/CHANGELOG.md
> Adding a first draft of a change log file

- src/fontra/views/applicationsettings/applicationsettings.html
- src/fontra/views/fontinfo/fontinfo.html
> Make the sidebar navigation match the width of the content

- src/fontra/client/core/var-glyph.js
- src/fontra/views/editor/edit-behavior.js
movable, draggable, via EditBehavior
This is another draft PR on top of the other, because it's easier to see the changes related to **Make the background image editable**.
> Make the background image editable

- src/fontra/client/core/font-controller.js
- src/fontra/core/fonthandler.py
- src/fontra/views/editor/editor.js
This fixes #1793.
This also implements writing background image data from the front end.
> [background image] Make image data participate in copy/paste

- src/fontra/client/core/utils.js
- src/fontra/views/editor/editor.js
> [background image] Paste background image from PNG or JPEG clipboard

- src/fontra/views/editor/panel-selection-info.js
Add reset transform icon button for bg image in the selection info panel.
> [background image] Add reset transform icon button for bg image

- src/fontra/views/editor/cjk-design-frame.js
- src/fontra/views/editor/edit-tools-knife.js
> [knife tool] Add missing import

- src/fontra/client/web-components/ui-form.js
> Fix bg image colorize behavior on Safari

- src/fontra/backends/copy.py
- test-py/test_backends_copy.py
This fixes #1859.
This supersedes #1859.
> Prevent fontra-copy to copy a path onto itself, ie. ensure source and dest are different

- src/fontra/client/core/changes.js
> Fix casting of object properties

- src/fontra/client/web-components/glyphs-search-field.js
- src/fontra/client/web-components/glyphs-search-list.js
- src/fontra/views/editor/editor.html
- src/fontra/views/editor/editor.js
- src/fontra/views/editor/panel-glyph-search.js
Fixes #1856 
This PR splits GlyphsSearch into GlyphsSearchFiled and GlyphsSearchList. In preparation for #102
> Refactor GlyphsSearch

- src/fontra/views/editor/panel-transformation.js
> Bind path operation funcs early, rather than late

- src/fontra/client/web-components/glyphs-search-field.js
- src/fontra/client/web-components/glyphs-search-list.js
- Fixing regression caused by #1867
- Minor improvement by using SimpleElelemt
> [glyphs-search] fix regression caused by refactoring

- src/fontra/client/web-components/ui-form.js
- src/fontra/views/editor/panel-selection-info.js
- src/fontra/views/editor/panel-transformation.js
+ removes overflow settings from `ui-form`
+ moves overflow to panel sections
> Add scrollable sections to panel-selection-info, panel-transformation

- src/fontra/client/web-components/glyph-cell-view.js
> [font overview] fix shift-select / shift-arrow-keys

- src/fontra/client/web-components/ui-accordion.js
This is needed for the font overview.
> accordion: make alt-click on the header fold/unfold all items

- src/fontra/client/web-components/glyph-cell-view.js
- src/fontra/client/web-components/ui-accordion.js
- src/fontra/views/editor/panel-related-glyphs.js
- src/fontra/views/fontoverview/fontoverview.js
> [related glyphs] Refactor to use glyph-cell-view

- src/fontra/client/core/utils.js
- src/fontra/client/web-components/glyph-cell-view.js
- src/fontra/client/web-components/glyph-search-field.js
- src/fontra/client/web-components/ui-accordion.js
- src/fontra/views/editor/editor.js
- src/fontra/views/fontoverview/fontoverview.js
- src/fontra/views/fontoverview/panel-navigation.js
> [font overview] store UI settings in URL fragment

- src/fontra/core/remote.py
> Fix messageFromServer method signature

- test-js/test-classes.js
- test-js/test-support.js
> Avoid import assert

- src/fontra/client/core/fontra-menus.js
> Fix view URL redirection

- src/fontra/views/fontoverview/fontoverview.css
- src/fontra/views/fontoverview/fontoverview.js
> Add placeholder if no glyphs are found

- src/fontra/views/editor/editor.js
This fixes #1953 and supersedes #1955.
> Show subtools with right-click or control-click

- src/fontra/backends/designspace.py
- src/fontra/client/core/view-controller.js
- src/fontra/views/editor/editor.js
- src/fontra/views/fontinfo/fontinfo.js
- src/fontra/views/fontoverview/fontoverview.js
This moves some connection recovery logiv to ViewController, making behavior more consistent across views.
Among other things, this fixes #1817.
> Misc external change fixes

- src/fontra/views/fontoverview/panel-navigation.js
1. make the sources popup items list reflect changes in the font sources
2. make the source popup label reflect changes in the font sources
> [font overview] Make sources popup respond to changes in sources

- src/fontra/views/fontoverview/fontoverview.js
> [font overview] Force cell update on selected font-level changes

- scripts/rebuild_glyphset_presets.py
- src/fontra/client/data/glyphset-presets.json
See also https://github.com/googlefonts/fontra/discussions/1943#discussioncomment-11959920
> Add Koeberlin Latin 1.000

- scripts/rebuild_glyphset_presets.py
- src/fontra/client/data/glyphset-presets.json
Fix sorting in `rebuild_glyphset_presets.py` and write to file (remove print) + update data
> Fix sorting of koeberlins glyphsets

- src/fontra/views/editor/panel-reference-font.js
Fixes https://github.com/googlefonts/fontra/issues/2013
> Fix reference-font panel layout

- src/fontra/client/core/classes.json
- src/fontra/client/core/var-glyph.js
- src/fontra/core/classes.py
- test-js/test-var-glyph.js
This adds a customData field to the Component class.
Needed for https://github.com/googlefonts/fontra-glyphs/pull/76
> Add customData field for components

- src/fontra/backends/copy.py
- src/fontra/workflow/merger.py
- test-py/data/workflow/output-fork-merge.fontra/font-data.json
- test-py/data/workflow/output-scale.fontra/font-data.json
- test-py/data/workflow/output-scale.fontra/glyph-info.csv
- test-py/data/workflow/output-scale.fontra/glyphs/A^1.json
- test-py/data/workflow/output-scale.fontra/glyphs/B^1.json
- test-py/data/workflow/output-scale.fontra/kerning.csv
- test-py/data/workflow/output-subset-scale-kerning.fontra/font-data.json
- test-py/test_workflow.py
This was a serious oversight. This PR fixes #2044.
> Make fontra-copy/copyFont propagate the UnitsPerEm, and test this.

- src/fontra/backends/fontra.py
> [.fontra backend] Don't write kerning.csv if there isn't any kerning

- src/fontra/views/applicationsettings/panel-shortcuts.js
> Fix translation keys (within shortcuts)

- src/fontra/views/fontinfo/panel-sources.js
> Show warning before deleting a font source

- src/fontra/core/server.py
Fixes #2070, apparently those things are only regular expressions when they're captured.
> Fix redirects

- src/fontra/core/server.py
Also rework previous redirect route to be more explicit, so both redirects can use the same handler.
> Add redirect for not-so-old legacy format, too

- .gitignore
- src/fontra/core/server.py
> Fix login redirect

- src-js/fontra-core/src/event-utils.js
- src-js/fontra-webcomponents/src/menu-bar.js
- src-js/fontra-webcomponents/src/menu-panel.js
> Fix context-menu close #2068

- src-js/views-editor/src/editor.js
> Add customData, to ensure all fields are filled, ensuring the compatibility check can work

- src-js/fontra-core/src/glyph-controller.js
> Use copyComponent() so we don't miss customData

- package-lock.json
- package.json
- src-js/fontra-core/assets/lang/de.js
- src-js/fontra-core/assets/lang/en.js
- src-js/fontra-core/assets/lang/fr.js
- src-js/fontra-core/assets/lang/ja.js
- src-js/fontra-core/assets/lang/nl.js
- src-js/fontra-core/assets/lang/zh-CN.js
- src-js/fontra-core/src/font-controller.js
- src-js/fontra-core/src/fontra-menus.js
- src-js/views-fontinfo/src/fontinfo.js
- src-js/views-fontinfo/src/panel-base.js
- src-js/views-fontinfo/src/panel-opentype-feature-code.js
- src/fontra/core/fonthandler.py
> OpenType feature code editor

- src-js/views-fontinfo/src/panel-opentype-feature-code.js
> Add line wrapping for code editor

- src/fontra/backends/designspace.py
- test-py/test_backends_designspace.py
> [designspace/ufo] Fix background layers for sparse masters

- src-js/fontra-webcomponents/src/menu-panel.js
> Fix menu-panel keydown propagation

- src-js/fontra-webcomponents/src/ui-list.js
> Fix undefined in axis value

- src-js/fontra-webcomponents/src/menu-bar.js
- src-js/fontra-webcomponents/src/menu-panel.js
This optimizes the menu code and revises the menu navigation as proposed in https://github.com/googlefonts/fontra/issues/2113#issuecomment-2750458716
> Refactor and revise menu

- src-js/views-editor/src/panel-designspace-navigation.js
...this includes change of edit mode.
This fixes #2143.
> Also update various things when the selectedGlyph object changes

- src-js/views-editor/src/panel-reference-font.js
Fixes #2157
@justvanrossum I was wondering if the layout becomes easier if the upload-list and the preview get joined. What do you think?
> Fix reference-font drop-area highlight border #2157

- src-js/fontra-core/src/font-controller.js
This is an optimization.
Cache a *promise* for a KerningController, not the KerningController itself, so we avoid getting the kerning data multiple times.
> Cache a promise for a KerningController, not the KerningController itself

- requirements-dev.txt
- src-js/fontra-core/assets/data/glyph-data.csv
Glyph data got updated, re-sync.
> Bump glyphslib dev requirement

- src/fontra/__main__.py
- src/fontra/core/server.py
https://github.com/googlefonts/fontra/issues/2180
> Use 'host' for free port finding, too

- src/fontra/backends/designspace.py
- test-py/test_backends_designspace.py
> Make sure we write the correct units-per-em to UFOs when exporting

- scripts/rebuild_glyphset_presets.py
- src-js/fontra-core/assets/data/glyphset-presets.json
> Add a Bengali glyph set

- src/fontra/workflow/merger.py
> Improve merging of Axes

- src/fontra/core/fonthandler.py
> When finishing a series of live changes, make sure to dispatch the final change to the non-live observers, too

- src-js/fontra-webcomponents/src/ui-form.js
Make ui-form-value have the same height as ui-form-label
> Fix a minor alignment issue in ui-form-value
