src/fontra/views/editor/editor.css

Suggesting a small refactor to both style the current textarea, and make these input styles generic.
Any <input type="text"> or <textarea> will automatically get default styling. If you want to make exceptions, like setting a width of an overflow, you can create a selector for that element only.
Fixes #131

Make styling for text inputs generic

---

src/fontra/core/server.py

I think the `launchWebBrowser` attribute was mistyped. Fixed some more things Pylance complained about. Why was `projectManager` of type `object` before instead of `FileSystemProjectManager`?
And what is the deal with `self.projectManager.setupWebRoutes(self)`? There seems to be no such method defined in the codebase.

Some more typing

---

src/fontra/backends/designspace.py

Don't round timestamps 'manually', but round-trip through datetime, ensuring the mtime we're getting from the raw filesystem matches the mtime we're getting via getGLIFModificationTime().
This fixes #132.

Fix file mtime timestamp rounding, solves #132

---

src/fontra/client/core/path-changes.js
src/fontra/client/core/utils.js
src/fontra/client/core/var-path.js
src/fontra/views/editor/edit-tools-pen.js
src/fontra/views/editor/edit-tools-pointer.js

Adding a recorder class to record path changes. This simplifies undo/redo-aware code a lot.

Refactor path changes

---

src/fontra/client/core/ui-form.js
src/fontra/views/editor/editor.js

Rewrote how the ui-form can notify clients of changes: provide a new onFieldChange handler that receives a valueStream iterator. This greatly simplifies how client code can be written.

UI form events

---

src/fontra/client/core/ui-dialog.js
src/fontra/client/css/ui-styling.css
src/fontra/views/editor/edit-tools-pointer.js

Towards implementing #52.
This shows a dialog when you double-click a placeholder glyph in the editor.
To be done in later PRs:
- Actually create a new glyph
- Figure out undo for glyph creation

Double-click on undefined glyph, show "create new glyph" dialog

---

src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js

- queue glyph writes (mostly to prevent two sequential changes to a single glyph being written out in parallel)
- catch write failures and recover from them, and notify the client

Schedule glyph writes

---

src/fontra/backends/designspace.py
test-py/test_font.py

Instead of having a full backend for a single UFO, just make up a axis-less designspace doc and use the DesignSpaceBackend. This gets rid of a nice chunk of redundant code.

Refactor UFOBackend to use DesignSpaceBackend

---

src/fontra/core/fonthandler.py

- Use generic match pattern code instead of peeking into change objects
- Add generic subscribe/unsubscribe remote methods
I also reimplemented `subscribeLiveGlyphChanges()` in terms of a match pattern, but ideally this remote method should be deleted. Using the new generic subscribe/unsubscribe methods for this was impractical, so more thinking is needed.

Use generic match pattern code instead of peeking into change objects

---

src/fontra/client/core/font-controller.js
src/fontra/core/changes.py
src/fontra/core/fonthandler.py
src/fontra/views/editor/scene-model.js

- Get rid of specialized subscribeLiveGlyphChanges
- Allow (un)subscribe(Live)Changes to take pattern dicts in addition to path lists
- Client keeps track of which glyphs have been subscribed to; use that to minimize (un)subscribe calls
To do:

Generalize subscribe

---

src/fontra/backends/designspace.py
src/fontra/backends/opentype.py
src/fontra/client/core/cmap.js
src/fontra/client/core/font-controller.js
src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js
test-js/test-cmap.js
test-py/test_font.py

Motivation:
- Unhappiness with the term "reverse cmap"
Solution:
- a "character map" maps characters (code points) to glyph names
- g "glyph map" maps glyph names to characters (code points)
TODO:

Rename "reverse cmap" to "glyph map" and "cmap" to "character map"

---

src/fontra/backends/designspace.py
src/fontra/backends/opentype.py
src/fontra/client/core/changes.js
src/fontra/core/changes.py
src/fontra/core/classes.py
src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js
test-py/test_changes.py
test-py/test_fonthandler.py

- Use LRU cache for local data
- Generalize writing to the backend
TODO:

Generalize "local data", to not be only for glyph data

---

src/fontra/backends/designspace.py
src/fontra/client/core/font-controller.js
src/fontra/core/fonthandler.py

Don't retrieve data just because it is referenced in a change: filter the change so it will only reference data we already have. Doing otherwise makes things much harder, especially when responding to external changes.

Rethink changes on uncached data

---

src/fontra/__main__.py
src/fontra/client/core/utils.js
src/fontra/client/settings.html
src/fontra/core/server.py
src/fontra/filesystem/landing.js
src/fontra/filesystem/projectmanager.py
src/fontra/views/editor/editor.js

This fixes #229.
- All outgoing HTML, CSS, and JS can get their links filtered so that a version token gets added
- All incoming static content requests will be checked for the version token, and will return 404 if it doesn't match
- Upon each launch of the Fontra server, use a random string for the version token
TODO:

Avoid browser cache problem by adding a version token to each asset filename

---

src/fontra/views/editor/editor.js

With this change, you have to double-click in the glyph list, or type enter, for the glyph to be inserted into the scene.
The main drive for this change is the desire to implement drag and drop from the list to a glyph-in-edit-mode to insert components.

[glyph list] Require double-click to switch glyphs

---

src/fontra/views/editor/editor.js

- replace dumb switch with flexible registry
- this enables a fix for #269: use plain 1, 2, 3 etc. keys to switch tools
Also fixes #269

Refactor shortcut handling

---

src/fontra/core/packedpath.py

Fixes #228.
- Add support for the new optional addVarComponent method, so we can read variable components from binary files.
Requires https://github.com/fonttools/fonttools/pull/2958

Read variable components from TTF

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/representation-cache.js

Use a general 'representation' mechanism for representations derived from the StaticGlyphController.
This makes it easier to (externally) add new kinds of representations for the StaticGlyphController, and simplifies the existing code.
(This is a simplified form of "representations" as used in [defcon](https://github.com/robotools/defcon/blob/2498713448294d9210adc1b0cd44f650672e7d24/Lib/defcon/__init__.py#L37), which were inspired by something I came up with before defcon was written.)

Use 'representations' mechanism for cached properties

---

src/fontra/client/core/context-menu.js
src/fontra/client/core/utils.js
src/fontra/client/css/context-menu.css

Fixes #255 
It adds shortcuts combinations to the items in the context menus if they exist. I haven't tested it on Windows but the code it's written, it should work properly replacing `⌘` with `Ctrl+` and so on.
Here are all possibilities for shortcut modifiers:
https://apple.stackexchange.com/a/55729/452817

Add shortcuts labels to the context menu items

---

src/fontra/views/editor/editor.js

Fix Safari ctrl+click context menu

---

src/fontra/core/clipboard.py
src/fontra/core/fonthandler.py
test-py/test_clipboard.py

Add support code to parse SVG and GLIF data. Part of #260.

Server-side clipboard support code: parse SVG + GLIF

---

src/fontra/client/core/change-recorder.js
src/fontra/client/core/font-controller.js
src/fontra/client/core/utils.js
src/fontra/client/core/var-path.js
src/fontra/core/clipboard.py
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-draw-funcs.js
test-py/test_clipboard.py

This implements paste from SVG and GLIF data. Part of #75 and #260.
To do:

Implement paste from SVG and GLIF data

---

src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js

Setting the selection on the sceneController had the same effect as passing it as part of the undo info block. Since the former is more flexible, I removed the latter route.

Rework undo selection protocol to not have two ways to do the same thing

---

src/fontra/backends/designspace.py
src/fontra/client/core/font-controller.js
src/fontra/core/clipboard.py
src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js
test-py/test_clipboard.py

This fixes #313.
- For now: put GLIF data on clipboard unconditionally, instead of SVG
- For now: do this via the server, as reimplementing in JS is more work
- Future: give the user an option between SVG, GLIF and JSON
~Perhaps needs a test case.~

Put GLIF data on plain text clipboard

---

src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js

Adding `sceneController.editInstanceAndRecordChanges()`, which combines `editInstance` and `recordChanges`, allowing to simplify several cases where the two are used in direct combination.

Refactor common editInstance + recordChanges combinations

---

.github/workflows/pytest.yml
src/fontra/views/editor/editor.js

(Ideally this would have its own item in the context menu, but maybe we need folding of menu items based on their key + modifiers, and have then change dynamically when the modifiers change.)

Make alt-delete behave like 'cut', without affecting the clipboard

---

src/fontra/client/core/font-controller.js
src/fontra/client/core/glyph-controller.js
src/fontra/client/core/glyph-glif.js
src/fontra/client/core/utils.js
src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js

Fixes #328.
- This adds a JS implementation to write GLIF data
- Removes the "pre-copy" logic on selection change
- Refactors a bit to mostly reuse the regular doCut and doCopy code

Rework event clipboard

---

src/fontra/views/editor/editor.js

The custom clipboard format was broken in 'regular' non-Safari workaround use: fix logic to work in all cases

The custom clipboard format was broken

---

src/fontra/client/core/utils.js
src/fontra/views/editor/editor.js

While this is redundant on Chrome, it simplifies the code, and makes the localSorage clipboard code behave consistently between Firefox and Safari.
Fixes #331

[clipboard] Always write clipboard to localStorage

---

src/fontra/client/core/utils.js
src/fontra/client/settings.html
src/fontra/client/web-components/general-settings.js
src/fontra/views/editor/editor.html
src/fontra/views/editor/editor.js

Fixes #316 
Separated settings in their own web component. `<general-settings/>`
My idea is that this can hold all logic which can be further broken down into modules/components. 
*`themeOptions` and `clipboardFormatOptions` are pretty much the same, they can be refactored to use less code but I think it is more convenient for altering them this way while still in the same component.

Add Settings panel to the sidebar

---

src/fontra/client/web-components/add-remove-buttons.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-model.js

Previously, the Add/Remove buttons were always visible, even if there were no sources to select. This shows and hides them according to the source list state

Show/hide the add/remove source buttons dynamically

---

src/fontra/views/editor/editor.js

We already detect SVG and GLIF, this PR adds support for JSON (our internal clipboard format).

Detect JSON when pasting plain text

---

src/fontra/client/core/observable-object.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/visualization-layers.js

- This adds an object Proxy wrapper allowing to observe shallow changes in an object (set/del property)
- Add a visualization layers settings object (for now: key = layer id, value = on/off)
- Subscribe to changes in the vis layer settings object for automatic redraw
Part of #239, needed for #254/#280
For a followup PR: fetch and store the settings from/to localStorage

Observable object layer prefs

---

src/fontra/client/core/ui-dialog.js

Change the 2nd arg of dialog() so it can alternatively be a function that has to return a DOM element.
The function will receive the content element.
Additionally, a button def can contain a `getResult` property, which then needs to be a function that returns the result for when that button is clicked.

Change the 2nd arg of dialog() so it can alternatively be a function

---

src/fontra/client/web-components/options-list.js
src/fontra/views/editor/editor.html
src/fontra/views/editor/editor.js
src/fontra/views/editor/visualization-layers.js

Fixes #254 
After Vizualisation Layers have been added, we can now manage to control those easily through the UI. 
At the moment only one 'section' or 'header' (Glyph display header) exists but more can be added easily.
Updated styling to match other sidebar panels:

Add layer preferences with Lit.js web component

---

src/fontra/views/editor/visualization-layer-definitions.js

The intention was to insert new layer defs in a way that:
- keeps the layer defs sorted by z index
- inserts *before* the item with a *higher* z-index, if any, else insert at the end
This PR makes the code behave as intended.

Fix z index

---

src/fontra/views/editor/editor.js

This works well, although perhaps I have altered the expected behaviour. What I imagine:
1. You enter for the first time, there are no settings. The defaults are set in the layers themselves. (In the current case both are false)
2. Then you change something > The layers appears on the screen + is stored in LocalStorage
3. Next time you enter we need to check whether anything is stored in LocalStorage. IF there is anything we use it, if not we use the default. 
** I am also triggering the actual layer otherwise all settings are synced but the layers don't show in practice. **

Save viz layer settings to local storage

---

src/fontra/views/editor/editor.js

Update designspace UI when a new glyph is created:
- Via an external change
- When the glyph was created here
This fixes #376.

Update designspace UI when a new glyph is created

---

src/fontra/views/editor/visualization-layer-definitions.js

Currently, the grid lines of the CJK Design Frame are one glyph unit thick, so they get thicker when you zoom in. I consider there a form of guidelines, and think they should be one pixel, regardless of zoom.

[cjk design frame] make grid lines one pixel instead of one unit

---

src/fontra/filesystem/projectmanager.py

Allow starting from a single font file instead of insisting on a folder.
This fixes #119.

[filesystem] Allow starting from a single font file

---

src/fontra/client/core/remote.js
src/fontra/views/editor/editor.js

When the websocket connection fails or gets closed (for example when the server shuts down), show a dialog with a "Try again" button.

Improve server error

---

src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/visualization-layer-definitions.js

Misc fixes regarding edit selection near/at neighboring glyphs:
- Clicking on selectable items of the edited glyph always has priority over clicking on a neighbor glyph
- Make hover behavior consistent with click behavior
- Keep path and nodes visible even if they are on top of a neighboring glyph
Unrelated: increase the "mouse click margin" a bit, so it's easier to grab things.

Selection fixes

---

src/fontra/client/core/path-hit-tester.js
src/fontra/client/core/utils.js
src/fontra/client/core/var-path.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js
test-js/test-path-hit-tester.js

When searching a point or segment under the mouse pointer, search from the *end*, so we'll find the topmost item in case there are multiple matches.

Reverse selection at point

---

src/fontra/client/core/convex-hull.js
src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/scene-model.js

Previously, if the shape of a glyph was completely contained within the convex hull of its right-hand neighbor, it would be impossible to click on (the right one always won).
This PR changes this behavior to be more useful by applying point-inside tests and a heuristic:
- check which glyph shape the user actually clicking on (do proper "point inside" testing)
- if that still doesn't resolve the issue (the target point is inside both shapes, or inside neither), take the glyph with the smallest area of its convex hull

Improve overlapping glyph selection

---

src/fontra/client/css/core.css
src/fontra/client/web-components/dialog-overlay.js
src/fontra/client/web-components/theme-support.js
src/fontra/client/web-components/ui-list.js

...as this turned out to be Chrome-only. Oops.
This also reworks the way the light/dark theme colors are switched, which makes it possible to use a global theme override in all web components without using :host-context.

Remove use of :host-context CSS

---

src/fontra/client/core/changes.js
src/fontra/client/core/classes.js
src/fontra/client/core/classes.json
src/fontra/client/core/font-controller.js
src/fontra/client/core/var-glyph.js
src/fontra/core/classes.py
src/fontra/core/server.py
test-js/test-classes.js

This was long coming, but only became necessary since new sources and layers can be created.
On the Python side, this has been in place for a while, via dataclasses, but this PR implements it for the JS client.
- Add classes.json, exported from classes.py
- Use the class schema to cast incoming raw objects to the appropriate types

Apply classes schema to incoming change data

---

src/fontra/client/core/classes.json
src/fontra/client/core/glyph-controller.js
src/fontra/client/core/var-glyph.js
src/fontra/core/classes.py
test-js/test-var-glyph.js
test-py/test_classes.py
test-py/test_font.py

Fixes #195, fixes #196, and fixes the Fontra side of https://github.com/googlefonts/fontra-rcjk/issues/25
- Add customData to VarGlyph, Source and Layer
- Add 'active' field to Source

Add customData to VarGlyph, Source and Layer

---

src/fontra/client/core/convex-hull.js
src/fontra/views/editor/edit-behavior.js
src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js

Towards implementing #386
This adds:
- User settings for experimental features
- Add opt-in "Scale edit tool behavior" experimental feature
The behavior is not great in some cases, and needs improvement. I label it "experimental" for now, so we can gather experience with it anyway.

Opt-in experimental scaling edit tool

---

src/fontra/views/editor/sidebar-designspace.js

When adding a new source, suggest a name based on the location instead of starting with an empty string.
Fixes #427.
Also, when editing source properties:
- If the source name still is as it was suggested, make it follow the axis sliders settings

[add source] Suggest a source name based on the location

---

src/fontra/views/editor/edit-tools-pen.js
src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js

Integrate path hit testing into selectionAtPoint. This is better factoring, but also allows me to fix #435, the selection Z order problem.

Fix segment selection on top of components

---

src/fontra/views/editor/edit-tools-hand.js

Ignore non-pointer events, which would mess up the origin calculation

---

src/fontra/client/core/font-controller.js
src/fontra/client/core/glyph-controller.js
src/fontra/client/core/observable-object.js
src/fontra/client/web-components/glyphs-search.js
src/fontra/client/web-components/ui-list.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js
src/fontra/views/editor/sidebar-designspace.js
src/fontra/views/editor/visualization-layer-definitions.js

Towards implementing #431.
- Add support for custom cells in ui-list
- Add optional columns header to ui-list
- Adds source list column for the "on" flag (or rather, "inactive", inverted)
- Adds support for drawing arbitrary layers in the background
- Adds "visible in background" column for source list
TODO (as followup PRs):
- Replace generic checkboxes with icons?
- Rethink the source list column titles
- Different colors for background glyphs
- Alignment of background glyph relative to selected? (Thinking of left/center/right, based on metrics)
- Way to easily turn on/off many/all background glyphs?

Multi column source list

---

src/fontra/views/editor/edit-tools-pen.js
src/fontra/views/editor/scene-model.js

Fixes #447.
This refactors selectionAtPoint into three separate methods.
The breakage in #447 was caused by the integration of pathHitAtPoint into selectionAtPoint. The refactoring gives more control to the caller without losing the convenience of the combined call.

Fix insert point bug

---

src/fontra/views/editor/scene-controller.js

Fixes #191 
This keeps the focused / selected / edited glyph better in view when playing around with the location sliders

Pin selected glyph to its horizontal center when the ds location changes

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/scene-model.js

Add isEmptyIsh glyph controller property, so we can fall back to 'empty' selection behavior if the glyph contains points but is invisible nevertheless.
This fixes #423.

Add isEmptyIsh glyph controller property

---

src/fontra/client/web-components/ui-list.js
src/fontra/views/editor/editor.js

What happened:
- UIList started to dispatch selection changed events if the items list was replaced
- this happens when you create a new glyph (the glyphs list changes after all)
- this triggered an even that made it behave as if the user clicked that glyph
- which would replace the new glyph that had just been created
Fixes #497.

Fix wrong display string after creating new glyph.

---

src/fontra/client/core/unlit.js
src/fontra/client/core/utils.js
src/fontra/client/web-components/glyphs-search.js

This implements two things:
1. If a character is entered in the search field, also search for the hex value of the code point as if it were entered as a search string. For example when entering "口" (U+53E3) in the search field, we also show results as if we'd be searching for the string 53E3, so we'd catch VG_53E3_00 in addition to the encoded uni53E3 character.
2. Parse any unencoded glyph name, and show a matching character if 4-6 char uppercase hex string is present in the glyph name, but in a dimmed color to show it is not a "real" encoded glyph.
Contrary to what I wrote in #499, this assumes hex uppercase in the glyph names, in an attempt to avoid false positives.
Fixes #499.

[glyphs search] Search for hex equivalent of char in glyph name / display pseudo char in list

---

src/fontra/views/editor/editor.js

For unencoded glyphs, try to fall back to the code point of the base glyph (glyph name without any extension).
This fixes #500.

For unencoded glyphs, try to fall back to the code point of the base glyph

---

src/fontra/client/core/utils.js
src/fontra/client/core/var-path.js
src/fontra/core/remote.py
src/fontra/core/server.py

- Use new `arrayExtend()` util instead of `array.push(...items)`, as the latter can overflow the JS call stack
- Increase the size limit for websocket messages
- Raise a better error if the size limit is exceeded
Fixes #507.

Work around and fix some datasize-related problems

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/var-path.js
test-js/test-var-path.js

The code to compute the flattened path for a component was overly complicated. This simplifies it somewhat.

Refactor component path

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/scene-model.js

- Click-select component: require the user to click on the actual shape
- Rect-select component: don't use the convex hull, but use the contour control polygons
Doing proper rect-shape intersection requires more work to implement and will be slower. Could still be a future refinement, via beziers.js, which implements line-curve intersection.
Fixes #524.

Refine selecting components

---

src/fontra/client/core/utils.js
src/fontra/client/core/var-model.js
src/fontra/views/editor/edit-behavior.js

As commented in https://github.com/googlefonts/fontra/issues/510#issuecomment-1585600740, we can just use `Math.sign()`, there's no need for our own implementation(s).

Remove redundant sign() function, use Math.sign() instead

---

src/fontra/client/core/utils.js
src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js

Rework point selection

---

src/fontra/client/core/utils.js

Followup to #508.
Without doc string it is conclear why this function exists at all, as noted in https://github.com/googlefonts/fontra/pull/533/files#r1227005997

Add doc string to arrayExtend() to explain its existence

---

src/fontra/client/core/font-controller.js
src/fontra/views/editor/scene-model.js

- Adds a `loadGlyphs()` method to the font controller class
- Call `loadGlyphs()` from `buildScene()`
Fixes #553.

Load all glyphs in parallel before we build the layout

---

src/fontra/views/editor/scene-model.js

Fixes #558
Don't skip adding empty positioned lines: else we mess up the relationship with the glyphLines input, which caused #558.

Don't skip adding empty positioned lines

---

src/fontra/client/web-components/add-remove-buttons.js

Fixes #445
Use inline-svg for + and - buttons instead of text. This fixes the alignment problem in Safari

Use inline-svg for + and - buttons instead of text

---

src/fontra/client/web-components/designspace-location.js
src/fontra/client/web-components/range-slider.js
src/fontra/views/editor/editor.html
src/fontra/views/editor/editor.js

Various fixes related to sidebar resizing.

---

src/fontra/client/core/observable-object.js
src/fontra/client/core/theme-settings.js
src/fontra/client/web-components/designspace-location.js
src/fontra/client/web-components/simple-settings.js
src/fontra/views/editor/cjk-design-frame.js
src/fontra/views/editor/edit-tools-power-ruler.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/sidebar-designspace.js
src/fontra/views/editor/sidebar-text-entry.js
test-js/test-observable-object.js

Change the signature of ObervableObject callbacks: they will now receive a single event object, with key, newValue and oldValue properties
This will make it easier for (near-) future expansion.

Change the signature of ObervableObject callbacks

---

src/fontra/client/core/observable-object.js
src/fontra/client/web-components/designspace-location.js
src/fontra/client/web-components/simple-settings.js
src/fontra/views/editor/sidebar-text-entry.js
test-js/test-observable-object.js

This moves the responsibility of ignoring an event to the event listener, and provides a more flexible way of communicating information from sender to listener.

ObservableObject: replace "skip listener" with "sender info"

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/sidebar-designspace.js

Work in progress, it will fix #591.

Can't edit glyph dialog refinement

---

src/fontra/views/editor/edit-tools-power-ruler.js
src/fontra/views/editor/scene-model.js

This fixes #631.
What happened:
- We used the positioned glyph to update the measurement
- But we get called at a time that the glyph lines have not yet been updated, so we'd look at stale data
To fix:
- Add getGlyphInstance(glyphName) method to SceneModel
- Refactor buildScene() as a mehod, which uses getGlyphInstance()
- The ruler now explicitly gets the instance and bypasses the glyph lines

Fix various ruler behaviors, eg. wrong measurements after arrow key nudge

---

src/fontra/core/server.py

Don't use mimetypes.guess_type() but use our own hard-coded table, so we are independent of system config flukes.
This fixes #646.

Don't use mimetypes.guess_type() but use our own hard-coded table

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/path-hit-tester.js
src/fontra/client/core/rectangle.js
src/fontra/client/core/var-path.js
src/fontra/client/css/ui-styling.css
src/fontra/views/editor/editor.js
src/fontra/views/editor/sidebar-selection-info.js
test-js/test-rectangle.js
test-js/test-var-path.js

This is a basic version of #345.
TODO:
- ~[ ] Selected component bounds does not update if the base glyph gets edited in another window~
This PR also adds proper bounds computing ("tight bounds", as opposed to control bounds).

Show selection dimensions info

---

src/fontra/client/core/canvas-controller.js
src/fontra/views/editor/editor.js

This removes some redundant event listening, and fixes the synchronisation between `sceneSettings.viewBox` and the actual view box.

Cleanup canvas resize

---

src/fontra/client/core/rectangle.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/sidebar-designspace.js

Fixes #688.
The important change here is to ensure we don't attempt to update the URL while we haven't even finished reading it.

Another attempt to fix #688

---

src/fontra/client/core/opfs-write-worker.js
src/fontra/client/core/utils.js
src/fontra/client/web-components/modal-dialog.js
src/fontra/client/web-components/reference-font.js
src/fontra/client/web-components/ui-list.js
src/fontra/views/editor/editor.js

Make reference font settings persistent by storing dropped font in the Origin Private File System (OPFS).
This PR fixes #519. Also fixes #686.

Make reference font settings persistent

---

src/fontra/backends/designspace.py
test-py/data/mutatorsans/MutatorSans.designspace

Also ignore the source layer name if it is set, but equals the default layer name.
This fixes #702.

[designspace backend] Ignore the source layer name if it is set, but equals the default layer name

---

src/fontra/client/core/utils.js
test-js/test-utils.js

- Continuation for #510.
- Fixed returning `rgb(` css function for rgba values
- Fixed error thrown when parsing cookie with trailing semicolon.

Write unittests for utils.js

---

src/fontra/core/fonthandler.py
src/fontra/core/server.py
src/fontra/filesystem/projectmanager.py

FontHandler instances are cached per access path, but they were never cleaned up, so it was not possible to reload underlying data unless the backend specifically implemented it. This change makes cleans up the FontHandler instance after the last connection using it goes away. Reloading a (single) page will now recreate the FontHandler.

[filesystem] Drop fonthandler when the last connection using it goes away

---

src/fontra/views/editor/editor.html

I would prefer to set the language when drawing text in the canvas, but I couldn't find a way. Setting the `lang` attr on the `<canvas>` element is at least effective.
This fixes #725.

Set canvas language to someting 'neutral', so that user language settings have no influence here

---

src/fontra/client/core/utils.js
src/fontra/views/editor/panel-text-entry.js

Restore focus after setSelectionRange() call, to work around Safari oddity.
This fixes #754.

Restore focus after setSelectionRange() call, to work around Safari oddity.

---

src/fontra/backends/designspace.py

Previously, it was decided on a per layer / per component basis whether it would be stored as a classic component or as a variable component.
This could mess up the component order if a component was considered variable in one source and not in another, even though that can be a perfectly compatible situation.
Additionally, if a component would use tCenterX/Y but no location, it would be stored as a classic component, thereby losing the tCenterX/Y information.
To avoid that, only write classic components if _all_ components in _all_ layers are classic (non-variable).
This fixes #585.

[designspace] Only write classic components if _all_ components in _all_ layers are classic

---

src/fontra/backends/designspace.py
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.weight=1/R_.alt.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.weight=1/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.width=1,weight=1/R_.alt.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.width=1,weight=1/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.width=1/R_.alt.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.width=1/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/R_.alt.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/layercontents.plist
test-py/test_backend_designspace.py
test-py/test_font.py

Several fixes related to local/global axis name conflicts.

Fix local global axis name conflict

---

src/fontra/client/core/glyph-controller.js

Rect-select: handle empty component: its controlBounds will be null/undefined

---

src/fontra/client/core/glyph-controller.js

Render a dotted placeholder square when a component references an empty glyph

---

src/fontra/views/editor/editor.js
src/fontra/views/editor/sidebar.js

Work in progress: Implement MIN_CANVAS_SPACE

---

src/fontra/client/web-components/ui-list.js

This fixes part of #293.
We can assume that the ui-list is always a vertically scrollable list, but it doesn't need always to be scrolled, so these are the changes:
- Horizontal scrollbars are always hidden.
- Vertical scrollbars are visible only if necessary.

[ui-list] Improve scrollbars behaviour.

---

src/fontra/client/web-components/designspace-location.js
src/fontra/client/web-components/grouped-settings.js
src/fontra/client/web-components/ui-form.js
src/fontra/filesystem/landing.css
src/fontra/views/editor/editor.css
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/panel-text-entry.js

Show scrollbars only if needed.

---

src/fontra/client/web-components/menu-panel.js

[context-menu] Fix wrong items vertical margins and left padding.

---

src/fontra/client/web-components/ui-form.js

This fixes #467.
Also improves text/number entry styling.
This also fixes a sizing issue, that relates to #300. The problem was a missing `box-sizing: border-box;`

Replace use of 'raw' range input with our range-slider

---

src/fontra/views/editor/panel-selection-info.js

This fixes #468.
Sort the component axes in the info panel, but lowercase first.

Sort axes, but lc first

---

src/fontra/client/core/var-path.js

...and drop (unused) support for raw coord array in path.addItemWise and path.subItemWise

Ensure 'other' argument is also VarPackedPath instance

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/var-model.js
src/fontra/client/tabler-icons/antenna-bars-1.svg
src/fontra/client/tabler-icons/antenna-bars-2.svg
src/fontra/client/tabler-icons/antenna-bars-3.svg
src/fontra/client/tabler-icons/antenna-bars-4.svg
src/fontra/client/tabler-icons/antenna-bars-5.svg
src/fontra/views/editor/panel-designspace-navigation.js
test-js/test-var-model.js

Fixes #660.
I'm deriving this info from the scalars + delta weights, but I'm not yet confident it is entirely correct.

Show the contribution of each source for the current location in a source list column

---

src/fontra/client/core/glyph-controller.js

This attempts to find a more likely candidate for the reference source, based on the balance between compatible and incompatible sources. It's still a bi of a heuristic, but is deterministic, and should work well in most cases.
Example 1:
- The default source is incompatible with all other sources, but all other sources are compatible with themselves, we should mark the default source as incompatible, and not the rest (as noted in https://github.com/googlefonts/fontra/issues/704#issuecomment-1723002207)
Example 2: 
- If among 5 sources 3 sources are compatible with each other, but not with the remaining two, which are also compatible with another, this will mark the set of two as the buggy ones, and not the set of three, regardless of the order of the sources.
This fixes #818.

Improve which sources are marked as "incompatible"

---

src/fontra/client/core/glyph-controller.js

Slight improvent on top of #819.
If we don't find the optimum reference layer, then use the default layer, and not the last we happened to look at

If we don't find the optimum reference layer, then use the default layer

---

src/fontra/client/web-components/designspace-location.js

Keep sliders as properties of an object instead of using element ids, so we don't have to worry about valid identifiers.
This fixes #821.

Keep sliders as properties of an object instead of using element ids

---

src/fontra/backends/designspace.py
src/fontra/client/core/font-controller.js
src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.rotate_end/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.rotate_end/nlitest.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.rotate_off/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs.rotate_off/nlitest.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/R_.alt.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/contents.plist
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/nlitest.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/varcotest2.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/layercontents.plist
test-py/test_font.py

Improve support for NLI by decoupling the editing layer from the location

---

src/fontra/client/web-components/ui-form.js
src/fontra/views/editor/panel-selection-info.js

Set default value on axis sliders, so alt-click does the expected thing, and the thumb gets style correctly at the default pos
This fixes #830.

[selection info panel] Set default value on axis sliders

---

.github/workflows/test.yml

Fix issue #834 by using the `pre-commit` GH action *(it caches installed hooks)*.
Running `pre-commit` is now much faster, before it took ~30s, now just ~10s.

Use `pre-commit` GitHub action.

---

src/fontra/views/editor/panel-designspace-navigation.js

This fixes #847.
In addition, it makes the header icon clickable: it will make all layers visible, or none, if any were visible before.

List header icon

---

.prettierrc

The code formatted using `prettier` with `pre-commit` is different from the code formatted when by the `JSPrettier` Sublime extension.
Explicitly set "trailing comma" option value in `.prettierrc` to avoid fallbacks to unexpected defaults.

Explicitly set "trailing comma" option value to avoid fallbacks to unexpected defaults.

---

src/fontra/client/core/changes.js
src/fontra/client/core/glyph-controller.js
src/fontra/client/core/path-functions.js
src/fontra/client/core/utils.js
src/fontra/client/core/vector.js
src/fontra/views/editor/edit-tools-pen.js
src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js
src/fontra/views/editor/visualization-layer-definitions.js

This implements various "multi-source editing" features.
This fixes #851, which includes:
- Fixes #75
- Fixes #493
- Fixes #643 
- Fixes #743
- Fixes #803 
- Fixes #844

Multi-source editing

---

src/fontra/views/editor/panel-selection-info.js
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/varcotest1.glif

Do rebuild the selection info completely if a component name changed

---

src/fontra/client/core/var-glyph.js
src/fontra/views/editor/editor.js

Copy component data before appending, to avoid sharing data

---

src/fontra/client/core/path-hit-tester.js
src/fontra/views/editor/scene-model.js

It turned out that it was easy to accidentally select a segment when trying to click on a point. This PR adds a margin around the points of the segment to make this less likely to happen.

Make it harder to accidentally click-select a segment

---

src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-user-settings.js

Make rect select not respond to live modifier changes by default; opt-in for the old behavior

Make rect select not respond to live modifier changes

---

src/fontra/client/core/path-functions.js
src/fontra/client/core/var-path.js
src/fontra/views/editor/edit-tools-pen.js

When drawing cubics, ensure that we don't build curves with a single off-curve point.

[pen tool] Draw no quads for cubics

---

src/fontra/client/core/changes.js
src/fontra/views/editor/edit-tools-pen.js
src/fontra/views/editor/visualization-layer-definitions.js

This fixes #308.
- When hovering over the final point, show an indicator:
- on-curve: dashed circle, "can drag off-curve from this point"
- off-curve: "cross": will delete off-curve when clicked
This also fixes a redundant undo record, when clicking bot not dragging a final on-curve point.

[pen tool] Improve hover visualization at end point

---

src/fontra/filesystem/projectmanager.py

When iterating a directory tree, skip folders we don't have permissions for

---

src/fontra/client/core/glyph-lines.js
src/fontra/client/core/utils.js
src/fontra/views/editor/panel-selection-info.js
test-js/test-utils.js

This fixes #895.
For unencoded glyphs that have a glyph name extension, try to look up the unicode for the "base" glyph (by stripping the extension), and show that as "Base unicode" in the selection info panel.

[info panel] Show "base" unicode for unencoded glyphs

---

src/fontra/core/fonthandler.py

- Schedule change broadcasts as tasks instead
- This introduces a fire-and-forget func called scheduleTaskAndLogException()
- Use scheduleTaskAndLogException() in other places, too
This fixes #897, as it preents "dormant", "frozen", "sleepy" browser tabs to block returning from editFinal, causing a lagging effect while editing..

Make broadcasting changes not block until all messages are sent

---

src/fontra/client/core/canvas-controller.js

Alternative to #925. 
Fixes #890:
Use some heuristics to detect a 'clunky' scroll wheel, and scale down deltaY to get more reasonable zoom and scroll behavior.
Fixes #891:
Implement shift scrollwheel to mean horizontal scroll.

Fix zoom / scroll with scroll wheel on Windows, second attempt

---

src/fontra/client/core/var-model.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-designspace-navigation.js

When doing multi-source paste, if a destination layer can't be found by name, try to look it up by source location.
This fixes #927.

Improve multi source paste

---

src/fontra/client/core/font-controller.js
src/fontra/client/core/utils.js
src/fontra/views/editor/editor.js

In edit mode, when pasting a whole glyph, ask the user whether they want to replace the glyph, or add to it.

Improve multi-source paste in edit mode

---

src/fontra/client/core/font-controller.js
src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/editor.js

This PR implements two things:
- Copy (multiple) layers in edit mode, paste in selecte mode. This fixes #947.
- Paste in non-existant glyph: this will create the glyph. This fixes #946.

Paste layers in selected glyph & paste in selected non-existant glyph

---

src/fontra/client/core/glyph-lines.js

- For `/å.alt` style glyph names, look up the base code point in the font itself first, and only fall back to getUnicodeFromGlyphName() when that wasn't successful
- Make isUndefined flag also work if we did find a glyph name earlier
This improves two things:
- If the character from the `/å` "fake" glyph name exists in the font, will find the correct glyph name, even if it is different from what the glyph name database suggests
- This avoids unneeded calls to `getUnicodeFromGlyphName()`, saving some network traffic

Avoid unneeded getUnicodeFromGlyphName() server calls

---

src/fontra/core/remote.py

When the user reloads the page before all glyphs are loaded, cancel all pending tasks, to avoid the inevitable errors while trying to answer back to the now closed websocket.

When the websocket closes, cancel all pending tasks

---

src/fontra/core/urlfragment.py
test-common/url-fragment-test-data.json

Don't escape non-ascii in the Python implementation of dumpURLFragment(): utf-8 is more compact, and this matches JSON.stringify().
Unfortunately we can't test non-BMP strings, as the Node fallback UTF-8 encoder in fflate doesn't support it properly. It works correctly in the browser, though.

dumpURLFragment() in Python: don't escape non-ascii

---

src/fontra/client/core/var-glyph.js
test-js/test-var-glyph.js

Fix regression caused by default field optimization: ensure all compo transformation fields are filled

---

src/fontra/backends/fontra.py
src/fontra/core/classes.py
src/fontra/core/path.py
src/fontra/core/remote.py
src/fontra/core/serverutils.py
test-py/test_classes.py
test-py/test_font.py
test-py/test_path.py

This makes Fontra play nicer with other apps that may use cattrs: we won't leak our hooks into other uses of cattrs.

Use central structure/unstructure funcs, so we can use a custom cattrs converter object

---

src/fontra/backends/fontra.py
src/fontra/client/core/classes.json
src/fontra/core/classes.py
test-common/fonts/MutatorSans.fontra/font-data.json

In the .fontra format, rename font.lib to font.customData, to be more in line with other customData fields.

rename font-level lib to customData

---

src/fontra/client/core/classes.json
src/fontra/core/classes.py
test-common/fonts/MutatorSans.fontra/font-data.json

This PR adds various fields and new types, so that our data structures are ready for these required features.
- `GlobalSource`
- `Guideline`
- `Anchor`
- `GlobalMetric`
This also adds a `locationBase` field to `Source`, so we can reference the location of a global source.

More types

---

src/fontra/core/clipboard.py
test-py/test_clipboard.py

This fixes #642.
And adds type annotations.

Clipboard fix for invalid input

---

src/fontra/client/web-components/range-slider.js

Discrete value range slider should be shorter

---

src/fontra/views/editor/panel-reference-font.js

Display current character in reference fonts

---

src/fontra/client/web-components/rotary-control.js
src/fontra/client/web-components/ui-form.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-selection-info.js

Rotary-like control for angles

---

src/fontra/client/core/var-model.js
test-js/test-var-model.js

Make normalizeLocation() not fail on invalid axes

---

src/fontra/views/editor/editor.js

Don't bail out on empty shape, use zero bounds for empty SVG

---

src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js

This fixes #1073.
This adds a shortcut (command-shift-D) for the Decompose Components context menu.
Additionally, this fixes the shortcut infrastructure to also use and respect the `enabled()` callback when a menu item is activated via a shortcut.

Add shortcut for Decompose Components

---

.pre-commit-config.yaml

We suddenly got flake8 warnings like:
```
icons/export-icons-as-svg.py:15:27: E231 missing whitespace after ':'
```
But the colon was embedded in an f-string, and this was a wrong warning. Upgrading to 7.0.0 fixes this.

Bump flake8 to 7.0.0: some of flake's dependencies may have broken f-string warnings

---

src/fontra/client/web-components/modal-dialog.js

No good way to close dialog elements via the backdrop, but it works nicely.
All other solutions found are doing calculations with getBoundingClientRect().
This fixes #1122.

close dialog via backdrop click

---

src/fontra/client/web-components/menu-panel.js

This fixes https://github.com/googlefonts/fontra/issues/1128.

Fixed selected item "enter" key confirmation to use appropriate event

---

src/fontra/client/web-components/menu-bar.js
src/fontra/client/web-components/menu-panel.js
src/fontra/views/editor/editor.js

Had to remove `event.stopImmediatePropagation()` from the `menu-panel.js` due to it blocking events being fired from `menu-bar.js`.
Please, tell me if this is something that might be breaking something (from my testing it was fine).
Also, I did a tiny fix for the "View" menu item since it didn't work and threw an error if nothing was typed to be shown inside the viewbox.
Any feedback is greatly appreciated!
This resolves https://github.com/googlefonts/fontra/issues/1134.
The "View" menu change fixes https://github.com/googlefonts/fontra/issues/1135.

1134 menu bar left right navigate

---

src/fontra/views/editor/editor.css

This is screenshot from chrome on windows

Fixes menu bar color in dark theme

---

src/fontra/workflow/workflow.py

Load optional/external actions via the 'fontra.workflow.actions' entry points

---

src/fontra/client/web-components/menu-bar.js
src/fontra/views/editor/editor.css

Now, menu bar height matches with container and the width doesn't overflow.
fix #1177

Tidy up the menu bar

---

src/fontra/workflow/actions.py
test-py/data/workflow/output-adjust-axes-no-mapping-no-source-remap.fontra/font-data.json
test-py/data/workflow/output-adjust-axes-no-mapping-no-source-remap.fontra/glyph-info.csv
test-py/data/workflow/output-adjust-axes-no-mapping-no-source-remap.fontra/glyphs/A^1.json
test-py/data/workflow/output-adjust-axes-no-source-remap.fontra/font-data.json
test-py/data/workflow/output-adjust-axes-no-source-remap.fontra/glyph-info.csv
test-py/data/workflow/output-adjust-axes-no-source-remap.fontra/glyphs/A^1.json
test-py/test_workflow.py

adjust-axes action: make remap sources optional

---

src/fontra/client/web-components/modal-dialog.js
src/fontra/views/editor/panel-designspace-navigation.js

This pr will fix this issue,
and fix #1176

Modal dialog improvement

---

src/fontra/core/instancer.py
src/fontra/workflow/actions.py
test-py/test_instancer.py

The word "flatten" is still used elsewhere in the code, where "decompose" would be better. But one step at a time.
In response to https://github.com/googlefonts/fontra/issues/1194#issuecomment-1988166591

Use 'decompose' instead of 'flatten'

---

src/fontra/backends/designspace.py
src/fontra/client/core/font-controller.js
src/fontra/client/core/lru-cache.js
src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js
src/fontra/views/fontinfo/fontinfo.js

This involved adding a special reload pattern (None/null) to indicate "reload all the things".
This also makes sure the list of paths to watch is kept up to date when adding new UFO sources.

Respond to external changes to .designspace files

---

src/fontra/backends/designspace.py
src/fontra/backends/utils.py
src/fontra/client/core/font-controller.js
src/fontra/core/fonthandler.py
src/fontra/core/glyphdependencies.py
src/fontra/core/server.py
src/fontra/core/subprocess.py
src/fontra/views/editor/editor.js
test-py/test_backends_designspace.py
test-py/test_glyphdependencies.py

- add fontra.backends.utils module for small functions that have no good other place
- add fontra.backends.glyphdependencies helper module to keep track of glyph dependencies
- rename `getGlyphsUsedBy()` to `findGlyphsThatUseGlyph()` (less ambiguous)
- add optional `startOptionalBackgroundTasks()` method to give backends a chance do some indexing without blocking regular loading

Implement "find glyphs that use glyph" for designspace backend

---

src/fontra/backends/fontra.py

Doing I/O exclusively with path objects allows us to drop in a different path object that writes to something that is not the system FS.

[fontra backend] Use path object throughout

---

src/fontra/backends/copy.py
src/fontra/workflow/actions.py
src/fontra/workflow/command.py
test-py/data/workflow/input-error-glyph.fontra/font-data.json
test-py/data/workflow/input-error-glyph.fontra/glyph-info.csv
test-py/data/workflow/input-error-glyph.fontra/glyphs/A^1.json
test-py/data/workflow/output-error-glyph.fontra/font-data.json
test-py/data/workflow/output-error-glyph.fontra/glyph-info.csv
test-py/test_workflow.py

This adds `--continue-on-error` options to `fontra-copy` and `fonta-workflow`, and `continueOnError` arguments to `copyFont()` and `action.process()`.
Useful with wip fonts that contain interpolation errors.

[copyFont] Optionally log getGlyph() errors and continue

---

pyproject.toml
src/fontra/core/clipboard.py

Account for different XML parse errors: the exact exception depends on whether lxml is installed or not.
We don't require lxml, but the tests failed once lxml was installed.

Account for different XML parse errors

---

src/fontra/workflow/merger.py
test-py/data/workflow/input-merge-codepoint-conflict.fontra/font-data.json
test-py/data/workflow/input-merge-codepoint-conflict.fontra/glyph-info.csv
test-py/data/workflow/input-merge-codepoint-conflict.fontra/glyphs/a.json
test-py/data/workflow/output-merge-codepoint-conflict.fontra/font-data.json
test-py/data/workflow/output-merge-codepoint-conflict.fontra/glyph-info.csv
test-py/data/workflow/output-merge-codepoint-conflict.fontra/glyphs/A^1.json
test-py/data/workflow/output-merge-codepoint-conflict.fontra/glyphs/B^1.json
test-py/data/workflow/output-merge-codepoint-conflict.fontra/glyphs/a.json
test-py/test_workflow.py

Previously, we naively merged two glyph maps, but this can result in a conflict when a code point is available in both fonts, but under different names.

[fontra-actions merge] Ensure we output a consistent glyphMap/cmap, without codepoint ambiguities

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/transform.js
src/fontra/views/editor/panel-transformation.js
test-js/test-transform.js

Put the functionality of transforming a decomposed transform into a function. This simplifies client code, and additionally makes us not lose the tCenterX/Y when decomposing a nested composite.

Simplify decomposed transformation

---

src/fontra/backends/designspace.py
src/fontra/client/core/classes.json
src/fontra/core/classes.py
test-py/data/avar2/DemoAvar2.designspace
test-py/test_backends_designspace.py

I modeled the Fontra mappings data structure after the designspaceLib *API*, not the format. I don't quite agree with the format (allowing multiple `<mappings>` sections), and am more at peace with the API (which emulates the grouping through the groupDescription attribute).
This is a followup for #1282.
This PR allows us to round-trip .designspace with `<mappings>` as well as the designspaceLib API allows.

[avar-2 designspace] Add support for mappings descriptions

---

src/fontra/backends/designspace.py
src/fontra/core/instancer.py
src/fontra/workflow/actions.py

It is possible (ie. we have data that contains examples) for source locations to contain values for axes that don't exist. Most likely an axis got deleted, but the source wasn't cleaned up. This can cause problems in a couple of places:
- The designspace backend would output too many sources, causing fontmake to chaoke
- Various axis manipulation actions in fontra-workflow could accidentally output non-unique source locations
This PR fixes both problems.

Protect against 'foreign' source location axis values

---

src/fontra/backends/designspace.py
test-py/test_backends_designspace.py

Fontmake will consider a designspace source sparse when it has its layername attribute set, even if it is the default layer name. This is fixed by not setting the layer name at all.

Don't set the layerName of a DS source if it is the default layer name

---

src/fontra/views/editor/sidebar.js

In `initResizeGutter()` of `views/editor/sidebar.js`:
https://github.com/googlefonts/fontra/blob/a723e8dc0d1613b7ee78d3bb64af49a1a99aeb58/src/fontra/views/editor/sidebar.js#L135-L156
width is initialized as `undefined`, and gets determined in the `onpointermove` event listener.
However, "clicking" does not triggers `pointermove` event, but only `pointerup` event.
So line 156 needs change, as width `undefined` is applied to the `applyWidth(width, saveLocalStroage)` method.
However also in line 179-181, null check is needed. https://github.com/googlefonts/fontra/blob/a723e8dc0d1613b7ee78d3bb64af49a1a99aeb58/src/fontra/views/editor/sidebar.js#L179-L181
Therefore I think refactoring `applyWidth(width, saveLocalStroage)` itself to contain null check is better.
This fixes #1303.

Fix #1303: first time clicking on the edge of a sidebar

---

src/fontra/client/web-components/modal-dialog.js

I found out that Material UI team had a similar issue: https://github.com/mui/material-ui/issues/22151
They solved it by ensuring that mousedown also happened "outside the dialog box", or "in a backdrop": https://github.com/mui/material-ui/pull/22310/files
First, I implemented it the same way as they did:
1. Record where mousedown happened.
2. Check in a click event listener that mousedown did happen in a backdrop.
But I changed two things:
1. To support more devices, I used pointerdown and pointerup events instead of mousedown and mouseup.
2. When I use click event for the main handler, the dialog closes if I start dragging outside of the dialog-box and then end dragging inside the dialog-box. I thought the only case the dialog closes should be when dragging both starts and ends outside …

Fix #1290: Dragging a slider in a dialog closes the dialog

---

src/fontra/workflow/actions.py
test-py/data/workflow/input-generate-palt-feature.fontra/font-data.json
test-py/data/workflow/input-generate-palt-feature.fontra/glyphs/A^1.json
test-py/data/workflow/output-generate-palt-feature.fontra/font-data.json
test-py/data/workflow/output-generate-palt-feature.fontra/glyphs/A^1.json

- Fix palt gen in the presence of an axis mapping (.fea needs user-space coords)
- Don't stop on buggy glyphs.
Continuation of #1322.

Misc generate-palt-feature action fixes

---

src/fontra/views/editor/editor.js

Don't handle space up when the active element is typable

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/scene-controller.js

First, I tried to match the style with previous component and path decomposing codes.
The case I paid extra attention is when the glyph and its component have anchors with same names;
For example, if somehow the parent glyph had a `top` anchor, and a compoment has a `top` anchor, only one of either anchors should remain, not both.
I chose to preserve anchors from the parent glyph. 
And as I was reading the code, decomposing supports decomposing multiple components at the same time. In that case, anchors from a component with a preceding order have priority.
This fixes #1315

Fix #1315: decompose component should include anchors

---

src/fontra/client/web-components/ui-list.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-designspace-navigation.js

To prepare for "virtual sources" and sorting of the glyph sources list, we need to make a clear distinction between the index into the glyph's sources list, and the index into the UI's representation of glyph sources.

Separate source index from UI list index

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/html-utils.js
src/fontra/client/tabler-icons/chevron-up.svg
src/fontra/client/web-components/icon-button.js
src/fontra/client/web-components/ui-accordion.js
src/fontra/views/editor/cjk-design-frame.js
src/fontra/views/editor/edit-tools-power-ruler.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js

- Redesign the designspace navigation panel to clearly separate font axes from glyph axes
- Use new ui-accordion web component, so we have three collapsable sections:
- font axes
- glyph axes
- glyph sources
Todo:

[wip] [avar2] Redesign designspace navigation panel, rework internal font location vs glyph location

---

src/fontra/views/editor/panel-designspace-navigation.js

`this.fontAxes` has the hidden axes filtered out, which we still need here.
This fixes #1386.

Use unfiltered fontAxes in Add source / Source properties dialog

---

src/fontra/backends/__init__.py
src/fontra/backends/copy.py
test-py/test_backends_copy.py

As well as a better error when the input font does not exist.

[fontra-copy] Better exceptions when trying to use unknown file types

---

src/fontra/views/editor/panel-designspace-navigation.js

Remove header icon for 'on' (active/inactive) source column, I find it distracting.

[source list] Remove header icon for 'on' (active/inactive) source column

---

src/fontra/client/core/var-path.js
src/fontra/views/editor/edit-tools-pointer.js
src/fontra/views/editor/scene-model.js

This fixes #572.
This improves selection behavior when multiple items (usually points) are close together.

Fix point selection: prefer items that are already selected

---

src/fontra/backends/designspace.py
src/fontra/workflow/actions/glyph.py
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/A_acute.glif
test-py/data/workflow/output-amend-glyph-custom-data.fontra/font-data.json
test-py/data/workflow/output-amend-glyph-custom-data.fontra/glyph-info.csv
test-py/data/workflow/output-amend-glyph-custom-data.fontra/glyphs/A^1.json
test-py/data/workflow/output-amend-glyph-custom-data.fontra/glyphs/B^1.json
test-py/test_font.py
test-py/test_workflow.py

This fixes #1450, by:
- Specifying a list of ufo glyph lib keys that belong to the default source, and should be kept in Fontra's glyph.customData
- Adding a fontra-workflow action that can add glyph.customData items

Create a way to communicate the OVERLAP_SIMPLE ttf flag via UFO

---

src/fontra/backends/designspace.py

Another approach for fix #1450:
Add an optional flag to the DS backend that, when set to true, will set the overlap flag in all exported layer glyphs.

Optionally set the 'overlap simple' flag for every exported glyph

---

src/fontra/views/editor/scene-model.js

Fix selection regressed behavior with points that overlap components

---

src/fontra/views/editor/editor.js

Fixes #1420 
I also extended the name behaviour with .trim(), so leading and trailing spaces will be deleted.

Fix editing glyph guideline with empty name (which is valid)

---

src/fontra/client/web-components/icon-button.js

After spending hours trying to solve the problem, I asked to chatGPT, and the first option it provided solved the problem.
I attach the solutions it suggested: https://chatgpt.com/share/68cc3cc6-7e15-4e8b-a29c-6fa3baba5c57
Since [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) of `will-change` recommends not to use `will-change` so often because it may cause too much resource consumption, I tried all the other solutions(animating only inner svg component,`transform-origin`, `backface-visibility`, `transformZ(0)`). However they all failed.
Thus I suggest adding `will-change: transform` to the style of `IconButton`.
This fixes #1388

Fix #1388: Icon hover animation misbehaves on Safari

---

src/fontra/client/core/ui-utils.js
src/fontra/views/editor/editor.js

Fixes #1339
I added a new option called selectOnFocus for textInput. This way we can have control over the textInput if it should be selected on focus or not. 
For reference:
https://github.com/googlefonts/fontra/assets/21055547/d75af2fc-b3bc-4dd6-8361-2193b09e19d2

Adding option selectOnFocus for textInput

---

src/fontra/workflow/actions/subset.py
test-py/data/workflow/input-drop-unreachable-glyphs.fontra/features.txt
test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyph-info.csv
test-py/data/workflow/input-drop-unreachable-glyphs.fontra/glyphs/A.alt^1.json
test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/features.txt
test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyph-info.csv
test-py/data/workflow/output-drop-unreachable-glyphs-composed.fontra/glyphs/A.alt^1.json
test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/features.txt
test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/glyph-info.csv
test-py/data/workflow/output-drop-unreachable-glyphs-decomposed.fontra/glyphs/A.alt^1.json

Use LayoutHandling.CLOSURE for drop-unreachable-glyphs, so we actually keep glyphs only reachable via features
Additionally (unrelated, but prevents a ufomerge warning), only add .notdef if we have it
This fixes #1481.

Use LayoutHandling.CLOSURE for drop-unreachable-glyphs

---

src/fontra/client/core/font-controller.js
src/fontra/client/core/glyph-controller.js
src/fontra/client/core/set-ops.js

Make the ComponentController to be async-free, as we'll need it to do bounds computations as part of the upcoming bounds resize addition for variable components. Inside an interactive edit loop we can't use async/await.

Refactor component controller

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/scene-model.js

Don't crash in selection code and getSelectionBounds() when anchors aren't compatible

---

src/fontra/backends/fontra.py

The .fontra kerning.csv reader would only read the first kern table, and skip any addition ones (say, vkrn). This PR fixes that. Testing will have to follow later, as changes it that area likely conflict with the ongoing work in https://github.com/googlefonts/fontra/pull/1518.

Fix multiple kerning read in .fontra format

---

src/fontra/views/editor/edit-tools-pointer.js

Fixes #1512 
I moved the whole code for 'bounds resize' up to the top of `handleDrag`. If `resizeHandle` exists, there is no need to go through the rest of the code. This fixes the glitch with the component vs. info panel. 
Plus: It is more close to what it was before we added the 'resize bounds'-feature.

Bugfix: Bounds Resize on component vs. info panel glitch

---

src/fontra/core/instancer.py

Mismatching guidelines should not be interpolation stoppers

---

src/fontra/client/web-components/menu-panel.js

If you see the code below, before, if the calculated bounding rect of the context menu exceeded the bounding rect of the canvas, the strategy was to modify x only by the "exceeding amount":
```Javascript
if (thisRect.right > containerRect.right) {
position.x -= thisRect.right - containerRect.right + 2;
// ...
}
```
More clearyly, when you view the positioning of the context menu, "the right margin" was fixed: if you click the menu close enough from the right border of the canvas, the context menu is always positioned 2 px apart from the right border of the canvas.
So is the case with the bottom positioning too.
That means if you click more than 2px apart, but still close enough from the right border, it can end up making your pointer located inside the context menu.
Therefore I made the …

Fix #1523: Change context menu positioning strategy to avoid edge case

---

src/fontra/core/fonthandler.py
test-py/test_fonthandler.py

I was seeing some intermittent teardown errors while running the tests, related to tasks not being shut down properly. So far, these changes seem to help.

Move task starting to startTask method; consistently call startTasks() in tests

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/core/path-functions.js
src/fontra/views/editor/edit-tools-pointer.js
test-js/test-glyph-controller.js

Fixes #1524 
The issues lives more deep into 
`getSelectionBounds` -> 
`filterPathByPointIndices` -> 
`getSelectionByContour` -> 
`getContourAndPointIndex`, 
when the selection does not match with the actual path/components. 
I first thought it would be good to fix it somewhere in getSelectionBounds, but probably this would change the behaviour too much???
Why I added a try/catch to getResizeBounds. 
I am happy to do it differently if you have an idea how to fix it in more proper way.

Fix: getResizeHandle error on incompatible source

---

src/fontra/workflow/merger.py
test-py/data/workflow/output-merge-kerning.fontra/kerning.csv

Previously, groups with the same name were merged as-is, which adds unwanted kerning to the merged font, and breaks the isdisjoint check for the values.

[fontra-workflow] Merge kerning: disambiguate group names instead of merging them blindly

---

src/fontra/client/lang/en.json
src/fontra/client/lang/zh-CN.json
src/fontra/client/web-components/glyph-cell.js
src/fontra/views/editor/panel-related-glyphs.js

Mainly:
- Hide sections that have no results
This way the panel looks more organized, and there's more space for the sections that _do_ have results.

[related glyphs] Some small improvements

---

.github/workflows/test.yml

~(But let's also try on 3.13, will undo if it causes trouble)~
We can't use 3.13 yet, it is blocked by https://github.com/samuelcolvin/watchfiles/issues/276

Run tests on 3.12

---

src/fontra/client/core/change-recorder.js
src/fontra/client/core/changes.js
src/fontra/core/changes.py

This fixes #1591, as an alternative to #1593.
This is a more thorough fix: the bug was caused by appendPath, that would cause changes at the individual PackedPath attributes, making it possible for pointAttributes to get mismatched.

Make explicit route for appendPath through change recording, so we don't hit pointAttribute clashes

---

src/fontra/client/core/path-functions.js
src/fontra/core/changes.py

This fixes #1591.
It is a bit of a workaround, but it does effectively prevent the error.
This is somewhat redundant after #1595, but is still a good cleanup.

Quick fix / workaround for the pointAttributes bug after using the knife tool

---

src/fontra/client/web-components/modal-dialog.js

Current behavior:
- dismiss a dialog by clicking on the backdrop
- the next time the dialog is triggered by a double click it will be dismissed immediately
Arguably, the dialog shouldn't receive this second click to begin with, but the `downInBackdrop` was never reset, causing the described behavior.
This fixes #1601.

[dialog] Don't misbehave after a dialog has been dismissed by clicking on the backdrop

---

src/fontra/client/core/actions.js
src/fontra/client/core/observable-object.js

Originally, the synch-with-local-storage mechanism could only cope with key/values that were explicitly declared on startup. However, we also need to be able to retrieve the stored keys. This is a bit risky, as it requires the prefix to be unique, and that there is no longer prefix that has the target prefix in common.

[observable-object] Optionally read the keys from localStorage

---

src/fontra/views/editor/edit-tools-shape.js

ShapeTool: Use commandKeyProperty instead of ctrlKey for reversed contour direction

---

src/fontra/views/editor/panel-transformation.js

Bugfix align objects: selection must be a set not array.

---

src/fontra/views/editor/editor.js

We call this.initFallbackClipboardEventListeners() elsewhere, and we shouldn't call it twice.
This fixes #1667.

Fix copy/paste on Safari

---

src/fontra/client/core/localization.js
src/fontra/core/server.py

Make json paths used in js file use the cache busting version token

---

src/fontra/client/lang/en.json
src/fontra/client/lang/zh-CN.json
src/fontra/views/editor/panel-transformation.js

Add actions to transformation panel

---

src/fontra/views/editor/visualization-layer-definitions.js

Fixes #1690 
Still draft PR, because I like the grey more. 
This is how it looks with the cjk.design.frame overshootColor:

Use overshootColor from cjk.design.frame

---

src/fontra/views/editor/edit-tools-pointer.js

Fixes #1702
Even though I don't know what the issue was caused by, it's already unnecessary to show the transformation handles if the file is readOnly or the glyph is locked – therefore I added code which don't show the handles if readOnly or glyph is locked.

Don't show transformation handles if readOnly or glyph locked

---

src/fontra/backends/designspace.py
test-py/test_backends_designspace.py

Previously, we could run into a situation where a layer with no glyphs would have no contents.plist, which makes various tools choke.

Ensure we write contents.plist, or we'll get an invalid ufo if no glyphs are ever added

---

src/fontra/workflow/actions/features.py
test-py/data/workflow/output-generate-kern-feature.fontra/features.txt
test-py/data/workflow/output-generate-kern-feature.fontra/font-data.json
test-py/data/workflow/output-generate-kern-feature.fontra/glyph-info.csv
test-py/data/workflow/output-generate-kern-feature.fontra/glyphs/A^1.json
test-py/data/workflow/output-generate-kern-feature.fontra/glyphs/B^1.json
test-py/test_workflow.py

ufo2ft splits kerning per script, but this can make kerning unavailable if the script isn't set "right". (This seems to happen with Kana kerning in Adobe Illustrator)
This workflow filter is dumb, and does not split kerning per script. I bet that has some downsides, too, but it may fix our Illustrator issue.

[fontra-workflow] Add generate-kern-feature filter, as an alternative to ufo2ft's kern feature generator

---

src/fontra/client/core/font-controller.js

If the FontSource's location is {}, it will be elided from the JSON dump. But when loading, we need to ensure it is there.
This fixes #1734.

Ensure sources have a location property

---

src/fontra/views/editor/editor.js

This fixes #1755.
This fixes a regression caused by https://github.com/googlefonts/fontra/pull/1636.

Fix action identifiers for cut/copy/paste

---

src/fontra/client/lang/de.js
src/fontra/client/lang/en.js
src/fontra/client/lang/fr.js
src/fontra/client/lang/nl.js
src/fontra/client/lang/zh-CN.js
src/fontra/views/editor/editor.js

Fixes #1751
This is a draft PR, as the displayed name has not yet been defined.
My comment on the google sheet:
```
VS Code: Show Release Notes
Chrome: Release Notes
As we don't do any official releases, here are some alternates:
Change Log
Update Notes
Version History
Software Update Notes
Version Notes
```
For reference, please see: https://docs.google.com/spreadsheets/d/1woTU8dZCHJh7yvdk-N1kgQBUj4Sn3SdRsbKgn6ltJQs/edit?pli=1&disco=AAABX4SxtcA

Add link to changelog page from Help menu

---

src/fontra/client/web-components/icon-button.js

As @justvanrossum said: https://github.com/googlefonts/fontra/issues/1759#issuecomment-2460640093, animating the svg inside the icon-button is indeed a good solution.
I changed the animating DOM object from the button itself to the svg inside the button.
I also added `will-change: transform` to the svg, in order to not to repeat the issue #1388.
Changing the animating object only didn't work in Windows. I added `contain: content` to the button, to indicate that the transform of its content should not affect the layout: https://developer.mozilla.org/en-US/docs/Web/CSS/contain
This fixes #1759

Fix #1759: Hovering over an icon can trigger the scroll bar

---

src/fontra/backends/designspace.py

We should get various mapping info the the default's glyph lib before we iterate over the layers: the first layer may not be the default, but still needs this info.

Fix flaw in designspace getGlyph()

---

src/fontra/client/core/font-sources-instancer.js
test-js/test-font-sources-instancer.js

New property:
- `defaultSourceIdentifier`
New method:
- `getLocationIdentifierForLocation()`
This is needed for #1662.

FontSourcesInstancer (JS) refactor + new prop + method

---

src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/scene-model.js

Fixes #1760 
Hi @justvanrossum , this is a possible solution, but I am not sure if this is the right path.
My thinking here is, that when the visualizationLayersSettings for guidelines is set to be 'hidden', the guidelines should not be part of the general selection. But to check the status of the guidelines visualizationLayersSettings we need `editorController`, but this hasn't been part of `SceneModel`, yet. And I think it may has a reason??? 
Therefore this is just a proposal to get in a conversation with you to get some advice.

Don't allow guideline selection, if they are hidden.

---

src/fontra/backends/designspace.py
src/fontra/views/editor/editor.js

Implement delete background image, and cut/copy/paste.
This fixes #1788.
This also fixed a bug with the designspace backend that prevented a background image reference to be deleted.
Copy/paste in this PR only deals with the background image _references_, and not yet the actual image data. Followup: #1793.

[background image] delete image, cut/copy/paste

---

src/fontra/backends/copy.py
src/fontra/backends/designspace.py
src/fontra/backends/fontra.py
src/fontra/core/protocols.py
test-py/test_backends_designspace.py

Get rid of redundant args to putBackgroundImage: turns out the designspace backend doesn't really need this after all, when put in some more effort.

[background image] Get rid of redundant args to putBackgroundImage()

---

src/fontra/client/core/utils.js
src/fontra/views/editor/editor.js

...but only if it's the only selected item.
This will *not* work in Safari over HTTP (ie. Fontra Pak), due to Safari not supporting the async clipboard API in that case. (To be clear, it does work in Safari when we run Fontra on HTTPS, but that's not the case with Fontra Pak.)
This fixes #1796.

[background image] On copy, put background image as image data on the clipboard

---

src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/visualization-layer-definitions.js

Followup to #1801
- Visualize hover state with different stroke color
- Ensure the bg image can't be selected if bg images are locked, no matter what (before this, they could still be selected via page reload and undo/redo)

[background image] Some fixups regarding bg image locking

---

src/fontra/backends/designspace.py
src/fontra/client/core/classes.json
src/fontra/client/core/var-glyph.js
src/fontra/client/lang/de.js
src/fontra/client/lang/en.js
src/fontra/client/lang/fr.js
src/fontra/client/lang/ja.js
src/fontra/client/lang/nl.js
src/fontra/client/lang/zh-CN.js
src/fontra/client/web-components/ui-form.js
src/fontra/core/classes.py
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/visualization-layer-definitions.js

This fixes #1803, and supersedes #1787.
This also adds an "opacity" field to the BackgroundImage class. It is easier to work with than with `backgroundImage.color.alpha`, esp. when the `color` field is optional. We'll leave the `color` field, but for now we won't expose it in the UI. (It is still useful for round-tripping UFO background images.)

[background image] Add support for background image in the selection info panel

---

src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js

- deselect bg image when hiding
- show bg images when unlocking
- don't add bg image in select all when bg images are hidden
- fix auto refresh bug when selection changes

[background image] Some image lock refinements

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/editor.css
src/fontra/views/editor/editor.js

This fixes #1807.
This also adds some checks so we don't offer image drop/paste when the backend doesn't support it.

[background image] Allow a PNG or JPEG file to be dropped onto a glyph in edit mode

---

pyproject.toml
requirements.txt
src/fontra/backends/designspace.py
test-py/test_backends_designspace.py

[background image] [designspace] Convert JPEG to PNG with Pillow as part of putBackgroundImage()

---

src/fontra/client/core/font-controller.js
src/fontra/client/core/utils.js
src/fontra/client/lang/de.js
src/fontra/client/lang/en.js
src/fontra/client/lang/fr.js
src/fontra/client/lang/ja.js
src/fontra/client/lang/nl.js
src/fontra/client/lang/zh-CN.js
src/fontra/client/web-components/ui-form.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/visualization-layer-definitions.js

This fixes #1814
This will supersede #1789
TODO:

[background image] Support colorization of the background image

---

src/fontra/views/editor/editor.js

This makes the context menu shorter. It was getting a bit out of hand. More to follow.

Turn Edit items into submenu in context menu

---

CHANGELOG.md
src/fontra/views/editor/scene-controller.js

This was previously left out because the context menu was getting too crowded. This is getting better now.

[background image] Add 'Add background image' menu to context menu

---

CHANGELOG.md
src/fontra/client/core/utils.js
src/fontra/client/web-components/icon-button.js
src/fontra/views/editor/panel-designspace-navigation.js

Keep focus if possible

---

src/fontra/workflow/actions/features.py
test-py/data/workflow/output-generate-vkrn-feature.fontra/features.txt

The kerning feature generator did properly emit "enum" qualifiers to "pos" statements for (possible) class exceptions.

Fix kerning feature generation

---

test-py/test_backends_workflow.py

Previously, this test code caused a warning on Python 3.13.

Make sure to aclose the backend to avoid a warning

---

src/fontra/workflow/merger.py
src/fontra/workflow/workflow.py
test-py/data/workflow/output-fork-A.fontra/font-data.json
test-py/data/workflow/output-fork-A.fontra/glyph-info.csv
test-py/data/workflow/output-fork-A.fontra/glyphs/A^1.json
test-py/data/workflow/output-fork-B.fontra/font-data.json
test-py/data/workflow/output-fork-B.fontra/glyph-info.csv
test-py/data/workflow/output-fork-B.fontra/glyphs/B^1.json
test-py/data/workflow/output-fork-merge.fontra/font-data.json
test-py/data/workflow/output-fork-merge.fontra/glyph-info.csv
test-py/data/workflow/output-fork-merge.fontra/glyphs/A^1.json
test-py/data/workflow/output-fork-merge.fontra/glyphs/B^1.json
test-py/test_workflow.py

With `fork:`, one can group multiple `output` steps and have common steps for pre-processing, without affecting the source pipeline.
With `fork-merge:` one can for example process a _subset_ of glyphs and merge the result back into the source pipeline.

[fontra-workflow] Implement "fork" and "fork-merge" step styles

---

src/fontra/client/core/font-controller.js
src/fontra/views/fontinfo/panel-sources.js

Fixes #1850
It would be great to have unittests for such methods, but I don't know how as we don't have any unittests for FontController, yet – and I don't know how to implement that. 
Also, I was thinking about to refactor `SourceBox` with replacing the arguments `this.fontAxesSourceSpace` and `sources` with `this.fontController` and then call `this.fontController.getSources()` and `mapAxesFromUserSpaceToSourceSpace` within `SourceBox`, but I think this has a negative impact to the performance, as we would do this then for each source while looping through all `sortedSourceIdentifiers`, why I didn't do it. 
So, I hope this PR is good to go.

Move sortedSourceIdentifiers to FontController

---

src/fontra/client/web-components/ui-form.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/panel-transformation.js

+ handle `ui-form` overflow and padding on `:host` (to prevent clipping)
+ add form modifier class for `selection-info` and `selection-transformation` (keeps flex settings within parent element scope)

fix: lock-button-tooltip #1768

---

src/fontra/client/web-components/ui-accordion.js
src/fontra/views/editor/panel-related-glyphs.js

Please see: https://github.com/googlefonts/fontra/pull/1866#issuecomment-2547865463

Add method showHideAccordionItem to Accordion class instead of findParentWithClass

---

src/fontra/views/editor/cjk-design-frame.js

This fixes a regression caused by https://github.com/googlefonts/fontra/commit/9d720da68a0a684a64a6dfbc195741f7c0f9a3dd
This caused the CJK Design Frame to be invisible for every new page, instead of keeping the previous setting.

Fix persistence of CJK Design Frame setting

---

src/fontra/client/web-components/glyphs-search-field.js
src/fontra/client/web-components/glyphs-search-list.js

This moves some responsibilities from glyphs-search-field to glyphs-search-list for a cleaner separation of concerns.
This also changes the use of the name `unicodes` to `codePoints`, like we do elsewhere.
This will break #1849, will fix there.

Glyphs search refactor 2

---

src/fontra/client/web-components/glyph-cell.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/scene-controller.js

- fix the cell with on Safari and Firefox
- make sure that we _do_ zoom-to-fit if we receive a URL in edit mode, but also turn off autoViewBox

Glyph cell width fix + autoViewBox fix

---

src/fontra/client/core/glyph-organizer.js
src/fontra/client/web-components/glyph-cell-view.js
src/fontra/client/web-components/glyph-cell.js
src/fontra/client/web-components/glyph-search-field.js
src/fontra/client/web-components/glyph-search-list.js
src/fontra/views/fontoverview/fontoverview.js
src/fontra/views/fontoverview/panel-navigation.js

- refactor glyph-search once more: move sort/filter functionality to new module
- use an observable settings object for the UI state
This paves the way to store the UI settings in the URL fragment. Part of #1886.

[font overview] use settings object

---

src/fontra/client/web-components/glyph-cell-view.js
src/fontra/client/web-components/glyph-cell.js
src/fontra/views/fontoverview/fontoverview.js

This PR does three independent things:
- Rework glyph-cell-view for "sections" (multiple accordion items), in preparation for #1887 
- Use a single IntersectionObserver instance for all cells instead of one per cell, in the hope that this is more efficient (still questionable)
- Fix location confusion between "user coordinates" and "source coordinates"

[font overview] misc refactoring

---

src/fontra/client/web-components/glyph-cell-view.js
src/fontra/views/fontoverview/fontoverview.js

This fixes #1897 
This PR adds:
- Arrow key selection (not yet with shift)
- Enter key to open the selection

[font overview] implement arrow key selection

---

src/fontra/views/editor/panel-related-glyphs.js

This is the follow-up of https://github.com/googlefonts/fontra/pull/1877
The change adjusts the box behavior of related glyphs panel so `calc(100% - 2em)` could be removed.
@justvanrossum I would suggest to set border-box globally. (read here https://css-tricks.com/almanac/properties/b/box-sizing/) I could improve this in a follow-up if you like.

Adjust related glyphs panel css

---

src/fontra/client/core/glyph-data.js
src/fontra/client/core/glyph-organizer.js
src/fontra/client/web-components/glyph-cell-view.js
src/fontra/views/fontoverview/fontoverview.css
src/fontra/views/fontoverview/fontoverview.js
src/fontra/views/fontoverview/panel-navigation.js

Part of #1886.
To be refined / discussed.

[font overview] implement a form of glyph/character grouping

---

src/fontra/client/core/glyph-organizer.js
src/fontra/client/web-components/glyph-cell-view.js
src/fontra/client/web-components/ui-accordion.js
src/fontra/views/fontoverview/fontoverview.js
src/fontra/views/fontoverview/panel-navigation.js

- Make section sorting more consistent
- Make section headers more consistent
- Remember which sections are closed
- Use term "group by" instead of "grouping" for variable names
This is part of #1886.

[font overview] Group By improvements

---

src/fontra/client/robots.txt
src/fontra/core/server.py

This fixes #1600.
Contains a minor refactoring that ensures we can serve `*.txt`.

Add robots.txt

---

src/fontra/client/core/glyph-organizer.js
src/fontra/client/core/utils.js
test-js/test-utils.js

- Look up the code points for the base glyph name (anything before the first dot in the name)
- Split the base glyph name by underscore so we can attempt to classify ligature glyphs (that use the underscore naming convention)

[font overview] improve grouping of unencoded glyphs

---

src/fontra/views/editor/editor.js

Add a conditional statement to ensure the multi-tool mousedown timer only affects the first child

---

src/fontra/client/core/path-functions.js

This fixes #1910, by processing the contours in reverse order (from back to front).

Delete points from contours in reverse contour order

---

src/fontra/core/fonthandler.py
src/fontra/views/editor/editor.js
types/remotefont.d.ts

Fixes #1878. FontraPak PR incoming.
~Also makes "find-glyphs-that-use-glyph" conditional on the server supporting it.~

Declare supported export formats in backend

---

src/fontra/client/core/html-utils.js
src/fontra/client/css/core.css
src/fontra/client/css/shadow-dom.js
src/fontra/client/css/shared.css
src/fontra/client/web-components/glyph-search-field.js
src/fontra/client/web-components/glyph-search-list.js
src/fontra/client/web-components/modal-dialog.js
src/fontra/client/web-components/ui-accordion.js
src/fontra/client/web-components/ui-form.js
src/fontra/client/web-components/ui-list.js
src/fontra/filesystem/landing.html
src/fontra/views/applicationsettings/applicationsettings.html
src/fontra/views/applicationsettings/panel-shortcuts.js
src/fontra/views/editor/editor.css
src/fontra/views/editor/editor.html
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel-glyph-note.js
src/fontra/views/editor/panel-glyph-search.js
src/fontra/views/editor/panel-reference-font.js
src/fontra/views/editor/panel-related-glyphs.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/panel-text-entry.js
src/fontra/views/editor/panel-transformation.js
src/fontra/views/fontinfo/fontinfo.html
src/fontra/views/fontoverview/fontoverview.css
src/fontra/views/fontoverview/fontoverview.html

Changes universal default `box-sizing` from `content-box` to `border-box`. (https://css-tricks.com/almanac/properties/b/box-sizing/)
An inconvenient side of this is that shadow-dom does not inherit such settings, however, a large part of the application components is shadow-dom. I actually wonder why? I think for most cases this is not recommendable.
As a solution here this introduces a `css/shadow-dom.js` file which gets appended in `SimpleElement` constructor (all shadow-dom components extend from this).
To avoid adjusting visual appearance  in this MR I set some elements individually back to `content-box` and marked them with `FIXME`. So they can be improved in a follow-up.

set universal css box-sizing to border-box

---

src/fontra/client/web-components/ui-accordion.js
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel-related-glyphs.js
src/fontra/views/fontoverview/fontoverview.css

Hey @giovanniTramonto, I was just running into a situation where it's undesirable to have Accordion do its own padding. I think this fixes it. Just in case you'd like to have a look? I immediately benefitted from the border-box improvement.

Remove padding from Accorion, and let clients deal with that

---

src/fontra/filesystem/landing.js

Even though the font overview isn't quite done, it is already very useful, so it's time to start using it from the landing page.

[landing page] Launch the font overview, not the editor

---

src/fontra/client/core/actions.js

It makes more sense to let the action machinery handle this than to add a dynamic title to a menu. 
It will allow us to differentiate between:
- registering a default title & default short cut for an action
- registering the implementation for an action that includes a dynamic title
We need this in #1925, where we need to register generic menu items without implementation (but with a default title), and views will provide their own implementations, with an optional dynamic title. This reduces the need to duplicate default shortcut definitions, and makes using a dynamic title clearer.

Allow actions to have a callback for a dynamic title

---

src/fontra/views/fontoverview/fontoverview.js

Example:
- the font contains `/Euro`, `U+20AC`
- a glyph set X defines `/euro`, `U+20AC`
When viewing glyph set X, `U+20AC` will show as `/Euro`, as that's what we have in the font.

[font overview] Put more effort into merging glyph sets in the face of conflicting glyph names for a code point

---

src/fontra/views/editor/panel-related-glyphs.js
src/fontra/views/fontoverview/fontoverview.css
src/fontra/views/fontoverview/fontoverview.js

- It should be _invisible_ by default, or you'll see it flash by before the glyph cells are made
- reversed the on/off logic, use class named 'shown'
- tweaked the color (made related glyphs equivalent match), so it looks better in dark mode
- shortened an overly long local variable
Followup to #1947.

[font overview] tweak no glyphs message

---

src/fontra/views/fontoverview/fontoverview.css
src/fontra/views/fontoverview/fontoverview.html
src/fontra/views/fontoverview/fontoverview.js
src/fontra/views/fontoverview/panel-navigation.js

Fixes #1948
Draft PR for feedback.
Do you mind to give me a hint how I can make the sliders change when changing the font source via the dropdown? It should work equal to the editor view when changing the source of a glyph, but I was not able to figure out how you implemented it.

Add location sliders to font overview

---

src/fontra/client/core/view-controller.js
src/fontra/views/editor/editor.js
src/fontra/views/fontinfo/fontinfo.js
src/fontra/views/fontoverview/fontoverview.js

view-controler.js:
- Add default implementation for start() (subclasses not need to call super.start())
- Move export-as actions to view-controller so all views automatically get this functionality
This fixes #1957

Move export-as actions to view-controller

---

src/fontra/client/core/view-controller.js
src/fontra/core/server.py
src/fontra/filesystem/landing.js

This fixes #1960, part of #1952. Supports redirecting existing URLs. I've chosen `?project=` as the query string parameter to hold the project ID. Assumes that URLs requesting static assets do not have a query string attached.

Use ?project= instead of /-/

---

src/fontra/views/fontoverview/fontoverview.js

To avoid showing no glyphs at all, select all project glyph sets. This fixes #1944.

[font overview] When no glyph sets are selected (including the font's own set), select all project sets

---

src/fontra/client/core/view-controller.js
src/fontra/views/editor/editor.js

This is enough to make external changes work in the font overview.
This fixes #1964.

Move reloadData() and minimal reloadEverything() and reloadGlyphs() to view-controller

---

src/fontra/client/core/parse-glyphset.js
src/fontra/views/fontoverview/fontoverview.js

When only a single glyphset it selected, we show the order of that glyph set.
This fixes #1971, to some extent at least.
This may need more thought and/or discussion.

[font overview] When overlaying multiple glyph sets, sort according to the builtin rules

---

src/fontra/client/core/path-functions.js

The `indices` array already has the `indexBias` applied, so should not be added here again.
This fixes #1980.

Fix bug with deleting multiple segments, one of which includes the starting point

---

src/fontra/client/core/font-controller.js
src/fontra/core/fonthandler.py

When deleting a glyphs raises an error, the glyphMap should also be reloaded.
This fixes #1978.

Recover more gracefully from glyph delete backend error

---

package.json
pyproject.toml
scripts/bundler_build_hook.py

This is a cosmetic change to the build system, aiming to minimise the invasiveness of #1952. When we move to bundling everything with webpack, it'll be a one-line change in package.json and there won't be odd references to `rollup` everywhere.

Make bundler actions generically named

---

src/fontra/views/applicationsettings/applicationsettings.html
src/fontra/views/applicationsettings/start.js
src/fontra/views/editor/editor.html
src/fontra/views/editor/start.js
src/fontra/views/fontinfo/fontinfo.html
src/fontra/views/fontinfo/start.js
src/fontra/views/fontoverview/fontoverview.html
src/fontra/views/fontoverview/start.js

This is another PR aimed at reducing the size of the #1952 change when it comes. It's good to have all the JS things in JS, not in HTML!

Move JS code from HTML to start.js

---

src/fontra/views/fontoverview/panel-navigation.js

Previously, the Location axes in the font overview would not be update when editing/adding/removing axes in the axes font info panel. This fixes that.

[font overview] Update the axes UI then the axes change

---

src/fontra/client/web-components/glyph-cell-view.js
src/fontra/views/editor/panel-related-glyphs.js

CSS only solution to peel off `displayMode` option from `glyph-cell-view`

Peel off glyph-cell-view displayMode option

---

src/fontra/client/css/shared.css
src/fontra/client/web-components/add-remove-buttons.js
src/fontra/client/web-components/icon-button.js
src/fontra/client/web-components/ui-accordion.js
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel-glyph-note.js
src/fontra/views/editor/panel-glyph-search.js
src/fontra/views/editor/panel-reference-font.js
src/fontra/views/editor/panel-related-glyphs.js
src/fontra/views/editor/panel-selection-info.js
src/fontra/views/editor/panel-text-entry.js
src/fontra/views/editor/panel-transformation.js
src/fontra/views/editor/panel.js
src/fontra/views/fontoverview/fontoverview.css
src/fontra/views/fontoverview/fontoverview.html
src/fontra/views/fontoverview/panel-navigation.js

Another attempt to make panel styles more consistent.
This time logic of `panel.js` did not change, but only reusable styles were added.
The node structure of all inheriting panels got harmonized to `.panel` wrapper containing `panel-section` and made a lot of styles redundant.

Add reusable css classes to panel view

---

src/fontra/views/editor/panel-reference-font.js

This fixes #2011.
These are regressions from #1918.

[reference font / opfs] iterDirectory will fail if the dir doesn't exist yet

---

src/fontra/views/fontinfo/fontinfo.html
src/fontra/views/fontinfo/fontinfo.js
src/fontra/views/fontinfo/panel-base.js
src/fontra/views/fontinfo/panel-sources.js

Fixes #1997
- I use "add-remove-buttons" (similar to other areas of Fontra) to add or remove a font source, this makes the repeating trash-icon redundant
- When adding a new font source, this will be 'selected'.
- With arrow up and down you can go to previous or next source (this will be ignored if the focus is for example on an input)

Rework font sources UI

---

src/fontra/views/editor/panel-transformation.js

styles are not in use anymore since https://github.com/googlefonts/fontra/commit/804117b4af67c8bfbf2c2f57c7c7dbeec9487f80

Remove redundant css from panel-transforamtion

---

src/fontra/client/core/glyph-organizer.js

- Allow regex for glyph name match;
- Use regex to find hex code points in glyph name
- Tighten the search by not allowing hex digits before and after the target string
When searching for "R", we also look for "0052" (code point for R in hex). But previously, this would also match (say) "10052", which can occur in "afii" glyph names. This PR tightens it to only match if the hex string has no hex digits before or after it. So "afii10052" no longer matches the search for "R".

Tighten hex code point search in glyph name

---

src/fontra/client/core/glyph-controller.js
src/fontra/views/editor/edit-tools-pointer.js

Don't show 'Transform selection' if only one point is selected

---

src/fontra/views/editor/panel-reference-font.js

Previously, an unset axis would result in an axis value of 'undefined' in the CSS, which is invalid.

[reference font] Improve reference font var location

---

src/fontra/client/core/font-controller.js
src/fontra/client/web-components/ui-list.js
src/fontra/views/editor/visualization-layer-definitions.js
src/fontra/views/fontinfo/panel-axes.js
src/fontra/views/fontinfo/panel-sources.js

Fixes #1963 #909 #2026
This allows adding/editing of font level guidelines via the sources panel. 
Currently it's not possible to edit font level guidelines within the editor view (we may want to create a new issue for this and see it as a follow up).
Quick demo:
https://github.com/user-attachments/assets/ad122b3b-ce95-43d1-98de-809658f33e2d

Add support for font guidelines

---

src/fontra/client/core/path-functions.js

When calculating the start/end tangents of a segment, ignore points that overlap with the first point.
This fixes #2033

[delete points] fix case when deleting a point that overlaps its neighbor

---

src/fontra/core/classes.py
src/fontra/views/fontinfo/panel-sources.js

- When serializing numbers, ensure they actually ar enumbers (float or int)
- Use NumberFormatter for italicAngle, so we write the value as a number
This fixes #2036.

[sources panel] Italic angle fix: write correct number type

---

src/fontra/client/core/html-utils.js
src/fontra/client/web-components/modal-dialog.js
src/fontra/client/web-components/ui-list.js
src/fontra/views/editor/panel-reference-font.js

Before reference-font items could only be deleted by selecting (clicking) an item and pressing delete-key after. Not self-explanatory. 
Now there is a remove (-) button at the end of each line.

Add reference-font remove button

---

src/fontra/client/core/glyph-lines.js
src/fontra/views/editor/panel-text-entry.js

These two small UI bugs were really bothering me so I fixed them.
1. `/slash` -> `/` -> *nothing* (or invalid character) (triggered by modification to the glyph lines such as by `cmd+left/right`)
2. Text area too tall for browser window, bad overflow behavior
Video demonstrating the bugs:
https://github.com/user-attachments/assets/7bf27d8e-d988-4aee-ba80-2c7ae572c29c
These are very trivial fixes, since I wanted to start off by contributing something small- but there are various improvements that would be desirable for the text panel, such as the ability to toggle whether to represent certain classes of glyphs as their character or `/name`, for example this is kind of annoying when working with combining glyphs since you may type `A/acutecomb` and have it turned in to `Á`, making it not …

Small bug fixes for text entry panel

---

src/fontra/client/core/ui-utils.js
src/fontra/client/css/core.css
src/fontra/client/css/shared.css
src/fontra/client/css/tooltip.css
src/fontra/client/web-components/glyph-cell-view.js
src/fontra/client/web-components/modal-dialog.js
src/fontra/client/web-components/simple-settings.js
src/fontra/client/web-components/ui-form.js
src/fontra/client/web-components/ui-list.js
src/fontra/views/applicationsettings/panel-shortcuts.js
src/fontra/views/editor/panel-reference-font.js
src/fontra/views/editor/panel-related-glyphs.js
src/fontra/views/editor/panel-selection-info.js

This sets document `white-space` back to `normal` (collapsed).
As mentioned in https://github.com/googlefonts/fontra/pull/1932#issuecomment-2615504160 I would recommend this. IMO it’s better for responsive behavior and avoids many overrides in the tree, since in most cases `nowrap` is an exception.

Remove css nowrap from body

---

src/fontra/client/core/path-functions.js

Second attempt to fix #2033.
When the selection is just a tangent point, then don't refit the curve, but only delete the tangent point itself.

Delete tangent point

---

src/fontra/client/css/tooltip.css
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/panel.js

This fixes the 2 bugs mentioned in https://github.com/googlefonts/fontra/issues/2050 
Tooltip line-height. The change in https://github.com/googlefonts/fontra/commit/ad2cb59ad4227a6bdb03df17738433128c6a4e41  was related to an issue with icons while scrolling, because of their line-height. In this case tooltip inherited the `0` line-height.
Tooltip cropping. This was was caused in a4edd57f4a7d8dc71ad495a494b4ab15ab00e2b5

Fix tooltips in sidebars #2050

---

src/fontra/client/core/utils.js
src/fontra/client/web-components/ui-list.js

ui-list paste plaintext-only

---

src/fontra/client/core/glyph-controller.js
src/fontra/client/lang/de.js
src/fontra/client/lang/en.js
src/fontra/client/lang/fr.js
src/fontra/client/lang/ja.js
src/fontra/client/lang/nl.js
src/fontra/client/lang/zh-CN.js
src/fontra/views/editor/editor.js
src/fontra/views/editor/panel-designspace-navigation.js
src/fontra/views/editor/scene-controller.js
src/fontra/views/editor/visualization-layer-definitions.js

Background layers, part 2

---

src-js/fontra-core/package.json
src-js/fontra-core/webpack.config.cjs
src-js/fontra-webcomponents/package.json
src-js/views-applicationsettings/package.json
src-js/views-editor/package.json
src-js/views-fontinfo/package.json
src-js/views-fontoverview/package.json
src/fontra/client/core/webpack-base.js
webpack.config.cjs

This is another non-invasive change as part of #1952. It adds a bunch of files which don't do anything right now, but will magically become relevant once we move the JS sources out of the Python tree.
Draft for now, because I'm going to make another branch on top of this locally to confirm I can do the migration and it all works.

JS package scaffolding

---

src-js/fontra-core/tests/test-utils.js

We have intermittent test failures, especially in Windows, but not only, that seem to be related to tests with timers. This tries to minimize that.

Tweak time-sensitive test, in the hope if will fail less frequently

---

src-js/fontra-core/src/change-recorder.js

Look up class names properly, don't hard-code them. The comment was right on.
This fixes #2078.

Look up class names properly, don't hard-code them.

---

src/fontra/backends/copy.py
src/fontra/backends/designspace.py
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/R_.alt.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/varcotest1.glif
test-py/data/mutatorsans/MutatorSansLightCondensed.ufo/glyphs/varcotest2.glif
test-py/test_backends_designspace.py
test-py/test_font.py
test-py/test_fonthandler.py

Towards #50.
- This adapts the fonts vs ufo layer name mapping to be compatible with the new bg layer naming convention
Todo:

Background layer support for .designspace / .ufo

---

.gitignore
package-lock.json
package.json
webpack.config.cjs

Hello,
I'm the author of the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).
I want to improve the Webpack configuration to save processed JS and CSS in separate folders.
Defaults Webpack places generated HTML, JS and CSS files into directory specified in the `output.path` Webpack option.
After running `npm run bundle`, the `src/fontra/client/` directory contains a mix of generated HTML, CSS, and JS files.
This PR allows configuring the Bundler Plugin to save JS and CSS, resolved in HTML, into separate directories:
- CSS -> `src/fontra/client/css/`
- JS -> `src/fontra/client/js/`
See  [js](https://github.com/webdiscus/html-bundler-webpack-plugin?tab=readme-ov-file#option-js) and [css](https://github.com/webdiscus/html-bundler-webpack-plugin?tab=read …

Improve webpack config for HtmlBundlerPlugin

---

CHANGELOG.md
src/fontra/backends/designspace.py
test-py/test_backends_designspace.py

This fixes #2040.
`putSources()` threw away ufo layer definitions for non-source layers.
This additionally fixes two bugs I found while fixing the original bug:
- fontSource.name was not written to the ds source styleName attribute
- ds source styleName attribute was not _read_ for sparse masters (non-default layerName)

[designspace] Fix editing sources

---

src-js/projectmanager-filesystem/landing.html
src-js/projectmanager-filesystem/package.json
src-js/projectmanager-filesystem/src/landing.js
src-js/projectmanager-filesystem/src/start.js

Split landing.js in two: start.js (script) and landing.js (importable module)

---

src-js/fontra-core/src/glyph-controller.js
src-js/views-editor/src/editor.js
src-js/views-editor/src/panel-designspace-navigation.js
src-js/views-editor/src/scene-controller.js

This is in preparation of https://github.com/googlefonts/fontra/issues/1639.
It further decouples the sources list UI from the `glyph.sources` list, allowing me to move forward to show global locations in the glyph source list UI.

Remove selectedSourceIndex sceneSettings field

---

src-js/fontra-core/src/canvas-controller.js
src-js/fontra-core/src/rectangle.js
src-js/fontra-core/src/utils.js
src-js/fontra-core/tests/test-rectangle.js
src-js/fontra-core/tests/test-utils.js

We're occasionally running into a big where the view box seemed to be messed up (with NaN, undefined, or other invalid numbers). This validates the view box on setting and getting, so we hopefully get a better error once this happens.
Also, do sanity checking on canvas magnification and origin values.

Validate canvas viewBox on getting and setting; add validateRect() func

---

src-js/fontra-webcomponents/src/custom-data-list.js

Fixes #2103
Because of `openTypeNamePreferredSubfamilyName` the width change is quite big.
Family level:
Font Source level:
And the total width is now 0.5em smaller then before, because I notices a small unneeded horizontal scroll.

Adjust custom data ui width of key column

---

package-lock.json
package.json
src-js/views-fontinfo/src/panel-opentype-feature-code.js

CodeMirror has its own undo, so we shouldn't use our undo mechanism, but we can hook up our undo/redo menus.

[feature editor] Fix undo confusion

---

src-js/fontra-webcomponents/src/ui-list.js

Problem:
- we have command-alt-arrow up/down shortcuts to switch source layers
- when the sources list has focus, doing command-alt-arrow will just navigate the sources list, and not the source layers list as expected
Fix this by ensuring no modifier keys are pressed in the UIList arrow key handler.

Prevent arrow up/down navigation in UIList to take over short cuts

---

src-js/views-editor/src/panel-designspace-navigation.js

This fixes #2123.
(This is still some fallout of the js-split operation.)

Fix URL manipulation for Edit font axes button

---

src/fontra/core/server.py

Do 403 if we don't have access to the requested project, or if it doesn't exist

---

src-js/fontra-core/src/glyph-data.js
src-js/fontra-core/src/utils.js
src-js/fontra-core/tests/test-glyph-data.js
src-js/fontra-webcomponents/src/glyph-cell.js
src-js/views-editor/src/visualization-layer-definitions.js

See the discussion in #2005
This works in the font overview, but I didn’t manage to find the relevant code in editor, so editing such glyphs still does not shows blank placeholder.

Guess glyph string for placeholder glyphs without code points

---

requirements.txt

As per https://pillow.readthedocs.io/en/stable/releasenotes/11.2.1.html version 11.2.0 is cancelled and removed from pypi.
Fix the broken dependency by bumping to 11.2.1 as recommended by upstream

Fix broken dependency with pillow 11.2.0

---

src-js/fontra-core/src/font-controller.js
src-js/fontra-core/src/remote.js
src-js/fontra-core/src/view-controller.js
src-js/views-editor/src/editor.js
src-js/views-editor/src/scene-model.js
src-js/views-fontinfo/src/fontinfo.js
src-js/views-fontoverview/src/fontoverview.js

This fixes a long standing bug with multiple views: after disconnect/reconnect (for example after the computer went to sleep and woke up again) the views would no longer respond to external changes. This is because server dropped the FontHandler, and subscription info was lost. Solve this by resubscribing to the relevant objects once we reconnect.

Fix subscriptions on reconnect

---

requirements.txt
src/fontra/workflow/features.py

ufomerge now can scale a UFO when merging, and for that it looks at ufo.info.unitsPerEm.
I'm not 100% we even need that functionality, since we have explicit scale tools in fontra-workflow, so for now it's fine to just hard-code that value to 1000.

Make ufomerge happy by providing an info object with a unitsPerEm attr

---

src/fontra/backends/designspace.py
test-py/test_backends_designspace.py

This fixes #2164.
This is important now that font source identifiers are also used as glyph layer identifiers, and we need the exact same identifiers if the backend gets reloaded, say after a computer sleep.

[designspace] make font source identifiers deterministic

---

src-js/fontra-core/src/kerning-controller.js

This fixes a bug where interpolated kerning would show the interpolated value as if the edit wasn't made.

Ensure to invalidate the pair function cache when we're editing kern pairs

---

src-js/views-editor/src/edit-tools-kerning.js

A pull request to allows jumping from 5 to 5 units when hold alt key and dragging the selector, or press arrows keys

Allows kerning jumps from 5 to 5 units

---

package-lock.json
package.json
src-js/views-fontinfo/src/panel-opentype-feature-code.js

Fixes #2186 #2101  and add indent with tab support
For color coding/syntax highlighting is using CodeMirror 5-style [stream parser](https://codemirror.net/docs/ref/#language.StreamParser) which may need to be upgraded for more advanced needs. But I think it works for now.
Undo/redo and toggle comment shortcuts still use codemirror keymaps.

Enhance OpenType feature code editor 2nd attempt

---

src-js/views-editor/src/edit-tools-metrics.js

When the text/glyph canvas contents changes, do not reset the metrics (sidebearing/kerning) selection, but filter out the invalid ones. This is especially nice together with the `/?` placeholder feature, as it allows the user to cycle through the font (command arrow L/R) and edit sidebearings without leaving the keyboard.

[metrics tools] Instead of zapping the selection, keep valid selectors

---

src-js/views-editor/src/edit-tools-metrics.js

When selecting one or more kerning pairs, hitting the delete key should delete the selected pairs across the entire designspace.
New behavior:
- delete: "deep delete": delete the selected pairs across the entire designspace
- alt-delete: only delete the selected pairs in the currently active designspace location
(The old behavior was the opposite.)

[Kerning tool] Reverse alt-key behavior with kerning delete key

---

src-js/fontra-core/assets/lang/de.js
src-js/fontra-core/assets/lang/en.js
src-js/fontra-core/assets/lang/fr.js
src-js/fontra-core/assets/lang/ja.js
src-js/fontra-core/assets/lang/nl.js
src-js/fontra-core/assets/lang/zh-CN.js
src-js/views-editor/src/edit-tools-metrics.js

Show a dialog when the one or more of the selected glyphs do not have a source at the current location

---

src-js/fontra-core/src/font-info-data.js
src-js/fontra-core/src/formatters.js
src-js/fontra-core/src/ui-utils.js
src-js/fontra-webcomponents/src/custom-data-list.js
src-js/fontra-webcomponents/src/ui-list.js
src-js/views-editor/src/panel-designspace-navigation.js
src-js/views-fontinfo/src/panel-axes.js
src-js/views-fontinfo/src/panel-sources.js

Move `DefaultFormatter`, `NumberFormatter` and `OptionalNumberFormatter` to formatters.js, where they belong.

[chore] Move DefaultFormatter, NumberFormatter and OptionalNumberFormatter

---

src-js/views-editor/src/scene-model.js

Currently, guidlines can only be selected at their anchor point. This PR allows clicking anywhere on the guideline.

Select (local) guidelines along line

---

src-js/fontra-core/src/simple-compute.js
src-js/fontra-core/tests/test-simple-compute.js
src-js/fontra-webcomponents/src/ui-form.js
src-js/views-editor/src/panel-selection-info.js

This fixes #2236.
This introduces an inline calculator in the metrics fields in the selection info panel. It evaluates to a concrete value once you type enter or leave the field.
It supports most common operators and parentheses. 
Additionally it allows to use glyph names as variable names, to refer to the metrics value for that glyph. For example, if you type `E` in the advance width field, it will take the advance width of the `E` glyph and put that in the field. Likewise, if you type `E` in the left sidebearing field, it will put the left sidebearing value from the `E` glyph in the field. But glyph names can also be used as part of an expression, for example `E + 10`.
There is a special notation for the *opposite* sidebearing, by adding a `!` to the glyph name: if in the _left_ …

Add expression evaluation to numeric metrics fields in selection info

---

src-js/fontra-core/src/changes.js
src-js/fontra-core/tests/test-change-recorder.js
src-js/fontra-core/tests/test-changes.js
src/fontra/core/changes.py
test-common/apply-change-test-data.json
test-py/test_changes.py

This fixes #2241.
The root cause was confusion regarding mutable objects that got shared in/via change objects that should not have been shared. The fix should be thorough and watertight, but might come at the expense of some performance, although I doubt this will be noticable in most common cases.

Don't share mutable objects into change objects, and from change objects

---

src-js/views-editor/src/editor.js

Case:
- press and hold space (enter clean view)
- press and hold command key
- release space key and command key (in any order)
We never receive a keyup event for the space key, so this leaves us in clean view, and with the hand tool selected.
This PR makes sure we also exit clean view in that case by listening to the keyup for the command key.

Make sure we exit 'clean view' in edge case
